export type CategoryNode = {
  id: string;
  name: string;
  // omit entirely for a true leaf; [] means "has children, not filled in yet"
  children?: CategoryNode[];
};

const APPAREL_ACCESSORIES: CategoryNode = {
  id: "apparel-accessories",
  name: "Apparel & Accessories",
  children: [
    {
      id: "clothing",
      name: "Clothing",
      children: [
        {
          id: "activewear",
          name: "Activewear",
          children: [
            {
              id: "activewear-pants",
              name: "Activewear Pants",
              children: [
                { id: "joggers", name: "Joggers" },
                { id: "leggings", name: "Leggings" },
                { id: "shorts", name: "Shorts" },
                { id: "sweatpants", name: "Sweatpants" },
                { id: "tights", name: "Tights" },
                { id: "track-pants", name: "Track Pants" },
                { id: "training-pants", name: "Training Pants" },
                { id: "wind-pants", name: "Wind Pants" },
              ],
            },
            {
              id: "activewear-sweatshirts-hoodies",
              name: "Activewear Sweatshirts & Hoodies",
              children: [
                { id: "hoodies", name: "Hoodies" },
                { id: "sweatshirts", name: "Sweatshirts" },
                { id: "track-jackets", name: "Track Jackets" },
              ],
            },
            {
              id: "activewear-tops",
              name: "Activewear Tops",
              children: [
                { id: "base-layer-tops", name: "Base Layer Tops" },
                { id: "crop-tops", name: "Crop Tops" },
                { id: "t-shirts", name: "T-Shirts" },
                { id: "tank-tops", name: "Tank Tops" },
              ],
            },
            {
              id: "activewear-vests-jackets",
              name: "Activewear Vests & Jackets",
              children: [
                { id: "jackets", name: "Jackets" },
                { id: "vests", name: "Vests" },
              ],
            },
            { id: "boxing-shorts", name: "Boxing Shorts" },
            {
              id: "dance-dresses-skirts-costumes",
              name: "Dance Dresses, Skirts & Costumes",
              children: [
                { id: "dance-dresses", name: "Dance Dresses" },
                { id: "dance-skirts", name: "Dance Skirts" },
              ],
            },
            {
              id: "leotards-unitards",
              name: "Leotards & Unitards",
              children: [
                { id: "leotards", name: "Leotards" },
                { id: "triathlon-suits", name: "Triathlon Suits" },
                { id: "unitards", name: "Unitards" },
              ],
            },
            { id: "sports-bras", name: "Sports Bras" },
          ],
        },
        {
          id: "baby-childrens-clothing",
          name: "Baby & Children's Clothing",
          children: [
            {
              id: "baby-childrens-bottoms",
              name: "Baby & Children's Bottoms",
              children: [
                { id: "cargos", name: "Cargos" },
                { id: "chinos", name: "Chinos" },
                { id: "jeans", name: "Jeans" },
                { id: "jeggings", name: "Jeggings" },
                { id: "baby-childrens-bottoms-joggers", name: "Joggers" },
                { id: "baby-childrens-bottoms-leggings", name: "Leggings" },
                { id: "skirts", name: "Skirts" },
                { id: "skorts", name: "Skorts" },
                { id: "baby-childrens-bottoms-sweatpants", name: "Sweatpants" },
                { id: "trousers", name: "Trousers" },
              ],
            },
            { id: "baby-childrens-diaper-covers", name: "Baby & Children's Diaper Covers" },
            { id: "baby-childrens-dresses", name: "Baby & Children's Dresses" },
            { id: "baby-childrens-one-pieces", name: "Baby & Children's One-Pieces" },
            {
              id: "baby-childrens-outerwear",
              name: "Baby & Children's Outerwear",
              children: [
                {
                  id: "baby-childrens-coats-jackets",
                  name: "Baby & Children's Coats & Jackets",
                  children: [
                    { id: "bolero-jackets", name: "Bolero Jackets" },
                    { id: "bomber-jackets", name: "Bomber Jackets" },
                    { id: "capes", name: "Capes" },
                    { id: "motorcycle-outerwear", name: "Motorcycle Outerwear" },
                    { id: "overcoats", name: "Overcoats" },
                    { id: "parkas", name: "Parkas" },
                    { id: "pea-coats", name: "Pea Coats" },
                    { id: "ponchos", name: "Ponchos" },
                    { id: "puffer-jackets", name: "Puffer Jackets" },
                    { id: "rain-coats", name: "Rain Coats" },
                    { id: "sport-jackets", name: "Sport Jackets" },
                    { id: "baby-childrens-coats-jackets-track-jackets", name: "Track Jackets" },
                    { id: "trench-coats", name: "Trench Coats" },
                    { id: "trucker-jackets", name: "Trucker Jackets" },
                    { id: "windbreakers", name: "Windbreakers" },
                    { id: "wrap-coats", name: "Wrap Coats" },
                  ],
                },
                { id: "snow-pants-suits", name: "Snow Pants & Suits" },
              ],
            },
            { id: "baby-childrens-outfits", name: "Baby & Children's Outfits" },
            { id: "baby-childrens-sleepwear", name: "Baby & Children's Sleepwear" },
            { id: "baby-childrens-socks-tights", name: "Baby & Children's Socks & Tights" },
            {
              id: "baby-childrens-swimwear",
              name: "Baby & Children's Swimwear",
              children: [
                { id: "burkinis", name: "Burkinis" },
                { id: "classic-bikinis", name: "Classic Bikinis" },
                { id: "cover-ups", name: "Cover Ups" },
                { id: "one-piece-swimsuits", name: "One-Piece Swimsuits" },
                { id: "rash-guards", name: "Rash Guards" },
                { id: "skirtinis", name: "Skirtinis" },
                { id: "surf-tops", name: "Surf Tops" },
                { id: "swim-boxers", name: "Swim Boxers" },
                { id: "swim-briefs", name: "Swim Briefs" },
                { id: "swim-dresses", name: "Swim Dresses" },
                { id: "swim-jammers", name: "Swim Jammers" },
                { id: "swim-trunks", name: "Swim Trunks" },
                { id: "swimwear-tops", name: "Swimwear Tops" },
              ],
            },
            {
              id: "baby-childrens-tops",
              name: "Baby & Children's Tops",
              children: [
                { id: "bodysuits", name: "Bodysuits" },
                { id: "cardigans", name: "Cardigans" },
                { id: "baby-childrens-tops-hoodies", name: "Hoodies" },
                { id: "overshirts", name: "Overshirts" },
                { id: "polos", name: "Polos" },
                { id: "shirts", name: "Shirts" },
                { id: "sweaters", name: "Sweaters" },
                { id: "baby-childrens-tops-sweatshirts", name: "Sweatshirts" },
                { id: "baby-childrens-tops-t-shirts", name: "T-Shirts" },
                { id: "tunics", name: "Tunics" },
              ],
            },
            {
              id: "baby-childrens-underwear",
              name: "Baby & Children's Underwear",
              children: [
                {
                  id: "boys-underwear",
                  name: "Boys' Underwear",
                  children: [
                    { id: "boys-long-johns", name: "Boys' Long Johns" },
                    {
                      id: "boys-underpants",
                      name: "Boys' Underpants",
                      children: [
                        { id: "boxer-briefs", name: "Boxer Briefs" },
                        { id: "boxer-shorts", name: "Boxer Shorts" },
                        { id: "briefs", name: "Briefs" },
                        { id: "midway-briefs", name: "Midway Briefs" },
                        { id: "trunks", name: "Trunks" },
                      ],
                    },
                    { id: "boys-undershirts", name: "Boys' Undershirts" },
                  ],
                },
                {
                  id: "girls-underwear",
                  name: "Girls' Underwear",
                  children: [
                    { id: "girls-long-johns", name: "Girls' Long Johns" },
                    {
                      id: "girls-underpants",
                      name: "Girls' Underpants",
                      children: [
                        { id: "bikinis", name: "Bikinis" },
                        { id: "girls-underpants-boxer-briefs", name: "Boxer Briefs" },
                        { id: "boyshorts", name: "Boyshorts" },
                        { id: "girls-underpants-briefs", name: "Briefs" },
                        { id: "hipsters", name: "Hipsters" },
                        { id: "panties", name: "Panties" },
                        { id: "period-underwear", name: "Period Underwear" },
                        { id: "thongs", name: "Thongs" },
                      ],
                    },
                    {
                      id: "girls-undershirts",
                      name: "Girls' Undershirts",
                      children: [{ id: "first-bras", name: "First Bras" }],
                    },
                  ],
                },
                {
                  id: "toddler-underwear",
                  name: "Toddler Underwear",
                  children: [
                    { id: "toddler-underwear-boxer-briefs", name: "Boxer Briefs" },
                    { id: "boxers", name: "Boxers" },
                    { id: "toddler-underwear-briefs", name: "Briefs" },
                    { id: "toddler-underwear-panties", name: "Panties" },
                    { id: "toddler-underwear-training-pants", name: "Training Pants" },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: "clothing-tops",
          name: "Clothing Tops",
          children: [
            { id: "blouses", name: "Blouses" },
            { id: "clothing-tops-bodysuits", name: "Bodysuits" },
            { id: "clothing-tops-cardigans", name: "Cardigans" },
            { id: "corset-tops", name: "Corset Tops" },
            { id: "clothing-tops-hoodies", name: "Hoodies" },
            { id: "off-shoulder-tops", name: "Off Shoulder Top" },
            { id: "clothing-tops-overshirts", name: "Overshirts" },
            { id: "clothing-tops-polos", name: "Polos" },
            {
              id: "clothing-tops-shirts",
              name: "Shirts",
              children: [
                { id: "dress-shirts", name: "Dress Shirts" },
                { id: "henley-shirts", name: "Henley Shirts" },
              ],
            },
            { id: "clothing-tops-sweaters", name: "Sweaters" },
            { id: "clothing-tops-sweatshirts", name: "Sweatshirts" },
            { id: "clothing-tops-t-shirts", name: "T-Shirts" },
            { id: "clothing-tops-tank-tops", name: "Tank Tops" },
            { id: "clothing-tops-tunics", name: "Tunics" },
          ],
        },
        { id: "dresses", name: "Dresses" },
        {
          id: "lingerie",
          name: "Lingerie",
          children: [
            { id: "babydolls", name: "Babydolls" },
            { id: "lingerie-bodysuits", name: "Bodysuits" },
            {
              id: "bra-accessories",
              name: "Bra Accessories",
              children: [
                { id: "bra-hardware-findings", name: "Bra Hardware & Findings" },
                { id: "bra-strap-pads", name: "Bra Strap Pads" },
                {
                  id: "bra-straps-extenders",
                  name: "Bra Straps & Extenders",
                  children: [
                    { id: "bra-extenders", name: "Bra Extenders" },
                    { id: "bra-straps", name: "Bra Straps" },
                  ],
                },
                { id: "breast-enhancing-inserts", name: "Breast Enhancing Inserts" },
                { id: "breast-lift-tape", name: "Breast Lift Tape" },
                { id: "breast-petals-concealers", name: "Breast Petals & Concealers" },
              ],
            },
            { id: "bras", name: "Bras" },
            { id: "camisoles", name: "Camisoles" },
            { id: "corsets-bustiers", name: "Corsets & Bustiers" },
            { id: "hosiery", name: "Hosiery" },
            { id: "jock-straps", name: "Jock Straps" },
            {
              id: "lingerie-accessories",
              name: "Lingerie Accessories",
              children: [
                { id: "body-harnesses", name: "Body Harnesses" },
                { id: "fashion-body-tape", name: "Fashion & Body Tape" },
                { id: "garter-belts", name: "Garter Belts" },
                {
                  id: "garters",
                  name: "Garters",
                  children: [
                    { id: "shirttail-garters", name: "Shirttail Garters" },
                    { id: "sock-garters", name: "Sock Garters" },
                  ],
                },
                { id: "pantyhose", name: "Pantyhose" },
              ],
            },
            { id: "lingerie-sets", name: "Lingerie Sets" },
            {
              id: "petticoats-pettipants",
              name: "Petticoats & Pettipants",
              children: [
                { id: "petticoats", name: "Petticoats" },
                { id: "pettipants", name: "Pettipants" },
              ],
            },
            {
              id: "shapewear",
              name: "Shapewear",
              children: [
                { id: "arm-upper-body-shapers", name: "Arm & Upper Body Shapers" },
                { id: "shapewear-bodysuits", name: "Bodysuits" },
                { id: "full-body-shapes", name: "Full Body Shapes" },
                { id: "high-waisted-briefs", name: "High Waisted Briefs" },
                { id: "shaping-camisoles-tank-tops", name: "Shaping Camisoles & Tank Tops" },
                { id: "shaping-slips", name: "Shaping Slips" },
                { id: "thigh-slimmers", name: "Thigh Slimmers" },
                { id: "waist-cinchers", name: "Waist Cinchers" },
              ],
            },
            {
              id: "womens-underpants",
              name: "Women's Underpants",
              children: [
                { id: "womens-underpants-bikinis", name: "Bikinis" },
                { id: "bloomers", name: "Bloomers" },
                { id: "womens-underpants-boyshorts", name: "Boyshorts" },
                { id: "womens-underpants-briefs", name: "Briefs" },
                { id: "cheeky-panties", name: "Cheeky Panties" },
                { id: "g-strings", name: "G-Strings" },
                { id: "womens-underpants-hipsters", name: "Hipsters" },
                { id: "womens-underpants-period-underwear", name: "Period Underwear" },
                { id: "womens-underpants-thongs", name: "Thongs" },
              ],
            },
            { id: "womens-undershirts", name: "Women's Undershirts" },
            { id: "womens-underwear-slips", name: "Women's Underwear Slips" },
          ],
        },
        {
          id: "maternity-clothing",
          name: "Maternity Clothing",
          children: [
            { id: "maternity-dresses", name: "Maternity Dresses" },
            { id: "maternity-one-pieces", name: "Maternity One-Pieces" },
            { id: "maternity-outerwear", name: "Maternity Outerwear" },
            {
              id: "maternity-pants",
              name: "Maternity Pants",
              children: [
                { id: "capris", name: "Capris" },
                { id: "maternity-pants-cargos", name: "Cargos" },
                { id: "maternity-pants-chinos", name: "Chinos" },
                { id: "maternity-pants-jeans", name: "Jeans" },
                { id: "maternity-pants-jeggings", name: "Jeggings" },
                { id: "maternity-pants-joggers", name: "Joggers" },
                { id: "maternity-pants-leggings", name: "Leggings" },
                { id: "maternity-pants-shorts", name: "Shorts" },
                { id: "maternity-pants-skorts", name: "Skorts" },
                { id: "maternity-pants-tights", name: "Tights" },
                { id: "maternity-pants-trousers", name: "Trousers" },
              ],
            },
            {
              id: "maternity-shapewear-support-garments",
              name: "Maternity Shapewear & Support Garments",
            },
            { id: "maternity-skirts", name: "Maternity Skirts" },
            { id: "maternity-sleepwear", name: "Maternity Sleepwear" },
            {
              id: "maternity-swimwear",
              name: "Maternity Swimwear",
              children: [
                { id: "maternity-swimwear-burkinis", name: "Burkinis" },
                { id: "maternity-swimwear-classic-bikinis", name: "Classic Bikinis" },
                { id: "maternity-swimwear-cover-ups", name: "Cover Ups" },
                { id: "maternity-swimwear-one-piece-swimsuits", name: "One-Piece Swimsuits" },
                { id: "maternity-swimwear-swim-boxers", name: "Swim Boxers" },
                { id: "maternity-swimwear-swim-dresses", name: "Swim Dresses" },
                { id: "maternity-swimwear-swimwear-tops", name: "Swimwear Tops" },
              ],
            },
            {
              id: "maternity-tops",
              name: "Maternity Tops",
              children: [
                { id: "maternity-tops-blouses", name: "Blouses" },
                { id: "maternity-tops-bodysuits", name: "Bodysuits" },
                { id: "maternity-tops-cardigans", name: "Cardigans" },
                {
                  id: "nursing-shirts",
                  name: "Nursing Shirts",
                  children: [
                    { id: "nursing-hoodies", name: "Nursing Hoodies" },
                    { id: "nursing-sweatshirts", name: "Nursing Sweatshirts" },
                    { id: "nursing-t-shirts", name: "Nursing T-Shirts" },
                    { id: "nursing-tank-tops", name: "Nursing Tank Tops" },
                  ],
                },
                { id: "maternity-tops-overshirts", name: "Overshirts" },
                { id: "maternity-tops-shirts", name: "Shirts" },
                { id: "maternity-tops-t-shirts", name: "T-Shirts" },
                { id: "maternity-tops-tunics", name: "Tunics" },
              ],
            },
            { id: "maternity-underwear", name: "Maternity Underwear" },
            { id: "nursing-bras", name: "Nursing Bras" },
          ],
        },
        {
          id: "mens-undergarments",
          name: "Men's Undergarments",
          children: [
            { id: "mens-long-johns", name: "Men's Long Johns" },
            { id: "mens-undershirts", name: "Men's Undershirts" },
            {
              id: "mens-underwear",
              name: "Men's Underwear",
              children: [
                { id: "mens-underwear-boxer-briefs", name: "Boxer Briefs" },
                { id: "mens-underwear-boxer-shorts", name: "Boxer Shorts" },
                { id: "mens-underwear-briefs", name: "Briefs" },
                { id: "mens-underwear-hipsters", name: "Hipsters" },
                { id: "jockstraps", name: "Jockstraps" },
                { id: "mens-underwear-midway-briefs", name: "Midway Briefs" },
                { id: "mens-underwear-thongs", name: "Thongs" },
                { id: "mens-underwear-trunks", name: "Trunks" },
                { id: "undershorts", name: "Undershorts" },
              ],
            },
          ],
        },
        { id: "one-pieces", name: "One-Pieces" },
        {
          id: "outerwear",
          name: "Outerwear",
          children: [
            { id: "chaps", name: "Chaps" },
            {
              id: "coats-jackets",
              name: "Coats & Jackets",
              children: [
                { id: "blazers", name: "Blazers" },
                { id: "coats-jackets-bolero-jackets", name: "Bolero Jackets" },
                { id: "coats-jackets-bomber-jackets", name: "Bomber Jackets" },
                { id: "coats-jackets-capes", name: "Capes" },
                { id: "coats-jackets-overcoats", name: "Overcoats" },
                { id: "coats-jackets-parkas", name: "Parkas" },
                { id: "coats-jackets-pea-coats", name: "Pea Coats" },
                {
                  id: "coats-jackets-ponchos",
                  name: "Ponchos",
                  children: [
                    { id: "changing-surf-ponchos", name: "Changing & Surf Ponchos" },
                    { id: "rain-ponchos", name: "Rain Ponchos" },
                  ],
                },
                { id: "coats-jackets-puffer-jackets", name: "Puffer Jackets" },
                { id: "coats-jackets-rain-coats", name: "Rain Coats" },
                { id: "coats-jackets-sport-jackets", name: "Sport Jackets" },
                { id: "coats-jackets-track-jackets", name: "Track Jackets" },
                { id: "coats-jackets-trench-coats", name: "Trench Coats" },
                { id: "coats-jackets-trucker-jackets", name: "Trucker Jackets" },
                { id: "varsity-jackets", name: "Varsity Jackets" },
                { id: "coats-jackets-windbreakers", name: "Windbreakers" },
                { id: "coats-jackets-wrap-coats", name: "Wrap Coats" },
              ],
            },
            { id: "liners-insulators", name: "Liners & Insulators" },
            { id: "outerwear-motorcycle-outerwear", name: "Motorcycle Outerwear" },
            { id: "rain-pants", name: "Rain Pants" },
            { id: "rain-suits", name: "Rain Suits" },
            {
              id: "outerwear-snow-pants-suits",
              name: "Snow Pants & Suits",
              children: [
                { id: "snow-bibs", name: "Snow Bibs" },
                { id: "snow-pants", name: "Snow Pants" },
                { id: "snow-suits", name: "Snow Suits" },
              ],
            },
            { id: "outerwear-vests", name: "Vests" },
          ],
        },
        { id: "outfit-sets", name: "Outfit Sets" },
        {
          id: "pants",
          name: "Pants",
          children: [
            { id: "baggy-corporate-trousers", name: "Baggy Corporate Trousers" },
            { id: "baggy-jeans", name: "Baggy Jeans" },
            { id: "cargo-pants", name: "Cargo Pants" },
            { id: "pants-chinos", name: "Chinos" },
            { id: "baggy-joggers", name: "Baggy Joggers" },
            { id: "cuffed-joggers", name: "Cuffed Joggers" },
            { id: "harem-pants", name: "Harem Pants" },
            { id: "pants-jeans", name: "Jeans" },
            { id: "pants-jeggings", name: "Jeggings" },
            { id: "pants-joggers", name: "Joggers" },
            { id: "pants-leggings", name: "Leggings" },
            { id: "palazzo-pants", name: "Palazzo Pants" },
            { id: "skinny-joggers", name: "Skinny Joggers" },
            { id: "straight-joggers", name: "Straight Joggers" },
            { id: "pants-trousers", name: "Trousers" },
          ],
        },
        {
          id: "clothing-shorts",
          name: "Shorts",
          children: [
            { id: "bermudas", name: "Bermudas" },
            { id: "bum-shorts", name: "Bum Shorts" },
            { id: "cargo-shorts", name: "Cargo Shorts" },
            { id: "chino-shorts", name: "Chino Shorts" },
            { id: "denim-bum-shorts", name: "Denim Bum Shorts" },
            { id: "denim-jorts", name: "Denim Jorts" },
            { id: "denim-shorts", name: "Denim Shorts" },
            { id: "dolphin-shorts", name: "Dolphin Shorts" },
            { id: "jegging-shorts", name: "Jegging Shorts" },
            { id: "jogger-jorts", name: "Jogger Jorts" },
            { id: "jogger-shorts", name: "Jogger Shorts" },
            { id: "legging-shorts", name: "Legging Shorts" },
            { id: "short-trousers", name: "Short Trousers" },
          ],
        },
        { id: "clothing-skirts", name: "Skirts" },
        { id: "clothing-skorts", name: "Skorts" },
        {
          id: "sleepwear-loungewear",
          name: "Sleepwear & Loungewear",
          children: [
            { id: "long-johns", name: "Long Johns" },
            {
              id: "loungewear",
              name: "Loungewear",
              children: [
                {
                  id: "loungewear-bottoms",
                  name: "Loungewear Bottoms",
                  children: [
                    { id: "loungewear-bottoms-boxers", name: "Boxers" },
                    { id: "loungewear-bottoms-joggers", name: "Joggers" },
                    { id: "loungewear-bottoms-leggings", name: "Leggings" },
                    { id: "lounge-pants", name: "Lounge Pants" },
                    { id: "loungewear-bottoms-shorts", name: "Shorts" },
                    { id: "loungewear-bottoms-skirts", name: "Skirts" },
                  ],
                },
                { id: "loungewear-sets", name: "Loungewear Sets" },
                { id: "loungewear-tops", name: "Loungewear Tops" },
              ],
            },
            { id: "nightgowns", name: "Nightgowns" },
            { id: "onesies", name: "Onesies" },
            { id: "pajamas", name: "Pajamas" },
            { id: "robes", name: "Robes" },
            { id: "wearable-blankets-sleep-sacks", name: "Wearable Blankets & Sleep Sacks" },
          ],
        },
        {
          id: "socks",
          name: "Socks",
          children: [
            { id: "ankle-socks", name: "Ankle Socks" },
            { id: "athletic-socks", name: "Athletic Socks" },
            { id: "compression-socks", name: "Compression Socks" },
            { id: "crew-socks", name: "Crew Socks" },
            { id: "dance-socks", name: "Dance Socks" },
            { id: "dress-socks", name: "Dress Socks" },
            { id: "footie-socks", name: "Footie Socks" },
            { id: "heel-socks", name: "Heel Socks" },
            { id: "hold-up-socks", name: "Hold Up Socks" },
            { id: "knee-socks", name: "Knee Socks" },
            { id: "panty-socks", name: "Panty Socks" },
            { id: "sneaker-socks", name: "Sneaker Socks" },
            { id: "thermal-socks", name: "Thermal Socks" },
            { id: "toe-socks", name: "Toe Socks" },
          ],
        },
        {
          id: "suits",
          name: "Suits",
          children: [
            { id: "pant-suits", name: "Pant Suits" },
            { id: "skirt-suits", name: "Skirt Suits" },
            {
              id: "tuxedos",
              name: "Tuxedos",
              children: [
                { id: "tuxedo-jackets", name: "Tuxedo Jackets" },
                { id: "tuxedo-pants", name: "Tuxedo Pants" },
              ],
            },
            { id: "unstitched-suit-sets", name: "Unstitched Suit Sets" },
          ],
        },
        {
          id: "swimwear",
          name: "Swimwear",
          children: [
            { id: "boardshorts", name: "Boardshorts" },
            { id: "swimwear-burkinis", name: "Burkinis" },
            { id: "swimwear-classic-bikinis", name: "Classic Bikinis" },
            { id: "swimwear-cover-ups", name: "Cover Ups" },
            { id: "swimwear-one-piece-swimsuits", name: "One-Piece Swimsuits" },
            {
              id: "period-swimwear",
              name: "Period Swimwear",
              children: [
                { id: "period-bikinis", name: "Period Bikinis" },
                { id: "period-one-piece-swimsuits", name: "Period One-Piece Swimsuits" },
              ],
            },
            { id: "swimwear-rash-guards", name: "Rash Guards" },
            { id: "swimwear-surf-tops", name: "Surf Tops" },
            { id: "swimwear-swim-boxers", name: "Swim Boxers" },
            { id: "swimwear-swim-briefs", name: "Swim Briefs" },
            { id: "swimwear-swim-dresses", name: "Swim Dresses" },
            { id: "swimwear-swim-jammers", name: "Swim Jammers" },
            { id: "swim-leggings", name: "Swim Leggings" },
            { id: "swim-shorts", name: "Swim Shorts" },
            { id: "swim-skirts", name: "Swim Skirts" },
            { id: "swimwear-swimwear-tops", name: "Swimwear Tops" },
            { id: "tankinis", name: "Tankinis" },
          ],
        },
        {
          id: "traditional-ceremonial-clothing",
          name: "Traditional & Ceremonial Clothing",
          children: [
            { id: "abayas-jilbabs", name: "Abayas & Jilbabs" },
            { id: "baju-melayu", name: "Baju Melayu" },
            { id: "cheongsams", name: "Cheongsams" },
            { id: "dashikis", name: "Dashikis" },
            { id: "dirndls", name: "Dirndls" },
            { id: "hanboks", name: "Hanboks" },
            { id: "kaftans", name: "Kaftans" },
            { id: "kilts", name: "Kilts" },
            {
              id: "kimonos",
              name: "Kimonos",
              children: [
                { id: "haori-jackets", name: "Haori Jackets" },
                { id: "kimono-jackets-cardigans", name: "Kimono Jackets & Cardigans" },
                { id: "yukatas", name: "Yukatas" },
              ],
            },
            { id: "kurtas-kurta-sets", name: "Kurtas & Kurta Sets" },
            { id: "salwar-kameez-suit-sets", name: "Salwar Kameez & Suit Sets" },
            {
              id: "saris-lehengas",
              name: "Saris & Lehengas",
              children: [
                { id: "lehengas", name: "Lehengas" },
                { id: "saris", name: "Saris" },
              ],
            },
          ],
        },
        {
          id: "uniforms-workwear",
          name: "Uniforms & Workwear",
          children: [
            { id: "clergy-uniforms", name: "Clergy Uniforms" },
            {
              id: "contractor-pants-coveralls",
              name: "Contractor Pants & Coveralls",
              children: [
                { id: "bib-overalls", name: "Bib Overalls" },
                { id: "coveralls", name: "Coveralls" },
                { id: "work-pants", name: "Work Pants" },
              ],
            },
            { id: "flight-suits", name: "Flight Suits" },
            {
              id: "food-service-uniforms",
              name: "Food Service Uniforms",
              children: [
                { id: "chef-coats-jackets", name: "Chef Coats & Jackets" },
                { id: "chef-hats", name: "Chef Hats" },
                { id: "chef-pants-trousers", name: "Chef Pants & Trousers" },
                { id: "food-service-aprons", name: "Food Service Aprons" },
                { id: "food-service-hair-nets", name: "Food Service Hair Nets" },
                { id: "food-service-shirts-blouses", name: "Food Service Shirts & Blouses" },
              ],
            },
            { id: "housekeeping-uniforms", name: "Housekeeping Uniforms" },
            {
              id: "military-uniforms",
              name: "Military Uniforms",
              children: [
                { id: "combat-uniforms", name: "Combat Uniforms" },
                { id: "dress-uniforms", name: "Dress Uniforms" },
                { id: "military-coats-jackets", name: "Military Coats & Jackets" },
                { id: "military-insignia-badges", name: "Military Insignia & Badges" },
                { id: "military-patches", name: "Military Patches" },
                { id: "military-uniform-pants", name: "Military Uniform Pants" },
                { id: "military-uniform-shirts", name: "Military Uniform Shirts" },
              ],
            },
            {
              id: "school-uniforms",
              name: "School Uniforms",
              children: [
                {
                  id: "school-physical-education-uniforms",
                  name: "School Physical Education Uniforms",
                },
                {
                  id: "school-uniform-blazers-outerwear",
                  name: "School Uniform Blazers & Outerwear",
                },
                { id: "school-uniform-dresses-jumpers", name: "School Uniform Dresses & Jumpers" },
                { id: "school-uniform-pants-shorts", name: "School Uniform Pants & Shorts" },
                { id: "school-uniform-skirts", name: "School Uniform Skirts" },
                {
                  id: "school-uniform-sweaters-knitwear",
                  name: "School Uniform Sweaters & Knitwear",
                },
                { id: "school-uniform-tops", name: "School Uniform Tops" },
              ],
            },
            {
              id: "scrubs",
              name: "Scrubs",
              children: [
                { id: "scrub-dresses-skirts", name: "Scrub Dresses & Skirts" },
                { id: "scrub-jackets", name: "Scrub Jackets" },
                { id: "scrub-pants", name: "Scrub Pants" },
                { id: "scrub-sets", name: "Scrub Sets" },
                { id: "scrub-tops", name: "Scrub Tops" },
              ],
            },
            { id: "security-uniform-accessories", name: "Security Uniform Accessories" },
            {
              id: "security-uniforms",
              name: "Security Uniforms",
              children: [
                { id: "security-uniform-pants", name: "Security Uniform Pants" },
                { id: "security-uniform-shirts", name: "Security Uniform Shirts" },
              ],
            },
            {
              id: "sports-uniforms",
              name: "Sports Uniforms",
              children: [
                { id: "baseball-jerseys", name: "Baseball Jerseys" },
                { id: "basketball-jerseys", name: "Basketball Jerseys" },
                { id: "cricket-jerseys", name: "Cricket Jerseys" },
                { id: "cycling-jerseys", name: "Cycling Jerseys" },
                { id: "football-jerseys", name: "Football Jerseys" },
                { id: "hockey-jerseys", name: "Hockey Jerseys" },
                { id: "nfl-jerseys", name: "NFL Jerseys" },
                { id: "rugby-jerseys", name: "Rugby Jerseys" },
                { id: "running-jerseys", name: "Running Jerseys" },
                { id: "soccer-jerseys", name: "Soccer Jerseys" },
                { id: "volleyball-jerseys", name: "Volleyball Jerseys" },
              ],
            },
            { id: "white-coats", name: "White Coats" },
          ],
        },
        {
          id: "wedding-bridal-party-dresses",
          name: "Wedding & Bridal Party Dresses",
          children: [
            {
              id: "bridal-party-dresses",
              name: "Bridal Party Dresses",
              children: [
                { id: "bridesmaid-dresses", name: "Bridesmaid Dresses" },
                { id: "flower-girl-dresses", name: "Flower Girl Dresses" },
                { id: "junior-bridesmaid-dresses", name: "Junior Bridesmaid Dresses" },
                { id: "mother-of-the-bride-dresses", name: "Mother of the Bride Dresses" },
              ],
            },
            { id: "wedding-dresses", name: "Wedding Dresses" },
          ],
        },
      ],
    },
    {
      id: "clothing-accessories",
      name: "Clothing Accessories",
      children: [
        { id: "arm-warmers-sleeves", name: "Arm Warmers & Sleeves" },
        {
          id: "baby-childrens-clothing-accessories",
          name: "Baby & Children's Clothing Accessories",
          children: [
            { id: "baby-childrens-belts", name: "Baby & Children's Belts" },
            { id: "baby-childrens-gloves-mittens", name: "Baby & Children's Gloves & Mittens" },
            { id: "baby-childrens-hats", name: "Baby & Children's Hats" },
            { id: "baby-childrens-protective-wear", name: "Baby & Children's Protective Wear" },
          ],
        },
        { id: "balaclavas", name: "Balaclavas" },
        { id: "bandanas-headties", name: "Bandanas & Headties" },
        { id: "belt-buckles", name: "Belt Buckles" },
        { id: "belts", name: "Belts" },
        {
          id: "bridal-accessories",
          name: "Bridal Accessories",
          children: [
            { id: "bridal-dupattas-shawls", name: "Bridal Dupattas & Shawls" },
            { id: "bridal-garters", name: "Bridal Garters" },
            { id: "bridal-gloves", name: "Bridal Gloves" },
            { id: "bridal-sashes-belts", name: "Bridal Sashes & Belts" },
            { id: "bridal-tiaras-headpieces", name: "Bridal Tiaras & Headpieces" },
            { id: "bridal-veils", name: "Bridal Veils" },
          ],
        },
        { id: "button-studs", name: "Button Studs" },
        { id: "clothing-patches", name: "Clothing Patches" },
        { id: "collar-stays", name: "Collar Stays" },
        { id: "cufflinks", name: "Cufflinks" },
        { id: "decorative-fans", name: "Decorative Fans" },
        { id: "detachable-collars", name: "Detachable Collars" },
        { id: "earmuffs", name: "Earmuffs" },
        { id: "fashion-face-masks", name: "Fashion Face Masks" },
        { id: "gloves-mittens", name: "Gloves & Mittens" },
        {
          id: "hair-accessories",
          name: "Hair Accessories",
          children: [
            { id: "durags-hair-wraps", name: "Durags & Hair Wraps" },
            { id: "hair-bands", name: "Hair Bands" },
            { id: "hair-beads-cuffs", name: "Hair Beads & Cuffs" },
            {
              id: "hair-bun-volume-shapers",
              name: "Hair Bun & Volume Shapers",
              children: [
                { id: "clip-in-hair-buns", name: "Clip-In Hair Buns" },
                { id: "hair-donuts-bun-makers", name: "Hair Donuts & Bun Makers" },
              ],
            },
            { id: "hair-combs", name: "Hair Combs" },
            { id: "hair-extensions", name: "Hair Extensions" },
            { id: "hair-forks-sticks", name: "Hair Forks & Sticks" },
            { id: "hair-nets", name: "Hair Nets" },
            {
              id: "hair-pins-claws-clips",
              name: "Hair Pins, Claws & Clips",
              children: [
                { id: "claw-clips", name: "Claw Clips" },
                { id: "hair-barrettes-slides", name: "Hair Barrettes & Slides" },
                { id: "hair-bows-bow-clips", name: "Hair Bows & Bow Clips" },
              ],
            },
            { id: "hair-wreaths", name: "Hair Wreaths" },
            { id: "headbands", name: "Headbands" },
            {
              id: "ponytail-holders",
              name: "Ponytail Holders",
              children: [
                { id: "scrunchies", name: "Scrunchies" },
                { id: "spiral-hair-ties", name: "Spiral Hair Ties" },
              ],
            },
            { id: "tiaras", name: "Tiaras" },
            { id: "wig-accessories", name: "Wig Accessories" },
            { id: "wigs", name: "Wigs" },
          ],
        },
        { id: "hand-muffs", name: "Hand Muffs" },
        { id: "handkerchiefs", name: "Handkerchiefs" },
        {
          id: "hats",
          name: "Hats",
          children: [
            { id: "baseball-caps", name: "Baseball Caps" },
            { id: "beanies", name: "Beanies" },
            { id: "berets", name: "Berets" },
            { id: "boater-hats", name: "Boater Hats" },
            { id: "bowler-hats", name: "Bowler Hats" },
            { id: "bucket-hats", name: "Bucket Hats" },
            { id: "cloche-hats", name: "Cloche Hats" },
            { id: "cowboy-hats", name: "Cowboy Hats" },
            { id: "fedoras", name: "Fedoras" },
            { id: "fezzes", name: "Fezzes" },
            { id: "flat-caps", name: "Flat Caps" },
            { id: "graduation-caps", name: "Graduation Caps" },
            { id: "kufis-topis", name: "Kufis & Topis" },
            { id: "newsboy-caps", name: "Newsboy Caps" },
            { id: "panama-hats", name: "Panama Hats" },
            { id: "pillbox-hats", name: "Pillbox Hats" },
            { id: "pork-pie-hats", name: "Pork Pie Hats" },
            { id: "snapback-caps", name: "Snapback Caps" },
            { id: "sombreros", name: "Sombreros" },
            { id: "sun-hats", name: "Sun Hats" },
            { id: "top-hats", name: "Top Hats" },
            { id: "trilbies", name: "Trilbies" },
            { id: "trucker-hats", name: "Trucker Hats" },
            { id: "visors", name: "Visors" },
            { id: "winter-hats", name: "Winter Hats" },
          ],
        },
        {
          id: "headwear",
          name: "Headwear",
          children: [
            { id: "bonnets-sleep-caps", name: "Bonnets & Sleep Caps" },
            { id: "fascinators", name: "Fascinators" },
            { id: "headdresses", name: "Headdresses" },
            { id: "turbans", name: "Turbans" },
            { id: "undercaps-underscarves", name: "Undercaps & Underscarves" },
          ],
        },
        { id: "leg-warmers", name: "Leg Warmers" },
        { id: "leis", name: "Leis" },
        { id: "maternity-belts-support-bands", name: "Maternity Belts & Support Bands" },
        { id: "neck-gaiters", name: "Neck Gaiters" },
        {
          id: "neckties",
          name: "Neckties",
          children: [
            { id: "ascots-cravats", name: "Ascots & Cravats" },
            { id: "bow-ties", name: "Bow Ties" },
            { id: "tie-sets", name: "Tie Sets" },
          ],
        },
        { id: "pinback-buttons", name: "Pinback Buttons" },
        { id: "pocket-squares", name: "Pocket Squares" },
        { id: "sashes", name: "Sashes" },
        { id: "scarves-shawls", name: "Scarves & Shawls" },
        {
          id: "sunglasses",
          name: "Sunglasses",
          children: [
            { id: "aviator-sunglasses", name: "Aviator Sunglasses" },
            { id: "cat-eye-sunglasses", name: "Cat-Eye Sunglasses" },
            { id: "oversized-sunglasses", name: "Oversized Sunglasses" },
            { id: "round-sunglasses", name: "Round Sunglasses" },
          ],
        },
        { id: "suspenders", name: "Suspenders" },
        { id: "tie-clips", name: "Tie Clips" },
        {
          id: "traditional-clothing-accessories",
          name: "Traditional Clothing Accessories",
          children: [
            { id: "bindis-forehead-adornments", name: "Bindis & Forehead Adornments" },
            { id: "cummerbunds", name: "Cummerbunds" },
            { id: "dupattas", name: "Dupattas" },
            { id: "graduation-regalia-accessories", name: "Graduation Regalia Accessories" },
            { id: "kilt-highland-wear-accessories", name: "Kilt & Highland Wear Accessories" },
            { id: "obi-belts", name: "Obi Belts" },
          ],
        },
        {
          id: "wristbands",
          name: "Wristbands",
          children: [
            { id: "awareness-wristbands", name: "Awareness Wristbands" },
            { id: "festival-event-wristbands", name: "Festival & Event Wristbands" },
            { id: "insect-repellent-wristbands", name: "Insect Repellent Wristbands" },
            { id: "survival-paracord-wristbands", name: "Survival & Paracord Wristbands" },
            { id: "sweat-wristbands", name: "Sweat Wristbands" },
          ],
        },
      ],
    },
    {
      id: "costumes-accessories",
      name: "Costumes & Accessories",
      children: [
        { id: "costume-accessories", name: "Costume Accessories" },
        { id: "costume-shoes", name: "Costume Shoes" },
        { id: "costume-wigs", name: "Costume Wigs" },
        {
          id: "costumes",
          name: "Costumes",
          children: [
            { id: "costume-cloaks-capes", name: "Costume Cloaks & Capes" },
            { id: "costume-dresses", name: "Costume Dresses" },
            { id: "costume-onesies-jumpsuits", name: "Costume Onesies & Jumpsuits" },
            { id: "costume-sets", name: "Costume Sets" },
            { id: "costume-tops", name: "Costume Tops" },
          ],
        },
        { id: "masks", name: "Masks" },
      ],
    },
    {
      id: "handbag-wallet-accessories",
      name: "Handbag & Wallet Accessories",
      children: [
        { id: "bag-bases-protectors", name: "Bag Bases & Protectors" },
        { id: "bag-charms", name: "Bag Charms" },
        { id: "bag-inserts-organizers", name: "Bag Inserts & Organizers" },
        { id: "bag-straps-handles", name: "Bag Straps & Handles" },
        { id: "keychains", name: "Keychains" },
        { id: "lanyards", name: "Lanyards" },
        { id: "purse-hooks-hangers", name: "Purse Hooks & Hangers" },
        { id: "wallet-chains", name: "Wallet Chains" },
      ],
    },
    {
      id: "handbags-wallets-cases",
      name: "Handbags, Wallets & Cases",
      children: [
        {
          id: "badge-pass-holders",
          name: "Badge & Pass Holders",
          children: [
            { id: "badge-reels", name: "Badge Reels" },
            { id: "id-card-holders", name: "ID Card Holders" },
            { id: "passport-holders", name: "Passport Holders" },
          ],
        },
        { id: "business-card-cases", name: "Business Card Cases" },
        { id: "checkbook-covers", name: "Checkbook Covers" },
        {
          id: "handbags",
          name: "Handbags",
          children: [
            { id: "backpack-handbags", name: "Backpack Handbags" },
            { id: "backpack-purses", name: "Backpack Purses" },
            { id: "baguette-bags", name: "Baguette Bags" },
            { id: "baguette-handbags", name: "Baguette Handbags" },
            { id: "barrel-bags", name: "Barrel Bags" },
            { id: "beach-bags", name: "Beach Bags" },
            { id: "belt-bags", name: "Belt Bags" },
            { id: "bucket-bags", name: "Bucket Bags" },
            { id: "clutch-bags", name: "Clutch Bags" },
            { id: "clutches", name: "Clutches" },
            { id: "convertible-bags", name: "Convertible Bags" },
            { id: "cross-body-bags", name: "Cross Body Bags" },
            { id: "crossbody-bags", name: "Crossbody Bags" },
            { id: "doctor-bags", name: "Doctor Bags" },
            { id: "envelope-clutches", name: "Envelope Clutches" },
            { id: "fold-over-clutches", name: "Fold Over Clutches" },
            { id: "half-moon-bags", name: "Half-Moon Bags" },
            { id: "hobo-bags", name: "Hobo Bags" },
            { id: "minaudieres", name: "Minaudieres" },
            { id: "mini-bags", name: "Mini Bags" },
            { id: "muff-clutches-bags", name: "Muff Clutches & Bags" },
            { id: "potli-bags", name: "Potli Bags" },
            { id: "saddle-bags", name: "Saddle Bags" },
            { id: "satchel-bags", name: "Satchel Bags" },
            { id: "satchels", name: "Satchels" },
            { id: "school-bags", name: "School Bags" },
            { id: "shopper-bags", name: "Shopper Bags" },
            { id: "shoulder-bags", name: "Shoulder Bags" },
            { id: "tote-bags", name: "Tote Bags" },
            { id: "trapezoid-bags", name: "Trapezoid Bags" },
          ],
        },
        {
          id: "wallets-money-clips",
          name: "Wallets & Money Clips",
          children: [
            { id: "card-cases", name: "Card Cases" },
            { id: "coin-purses", name: "Coin Purses" },
            { id: "key-cases", name: "Key Cases" },
            { id: "money-clips", name: "Money Clips" },
            { id: "neck-pouches", name: "Neck Pouches" },
            { id: "travel-wallets", name: "Travel Wallets" },
            { id: "wallets", name: "Wallets" },
            { id: "wrist-bags", name: "Wrist Bags" },
          ],
        },
      ],
    },
    {
      id: "jewelry",
      name: "Jewelry",
      children: [
        { id: "anklets", name: "Anklets" },
        { id: "body-jewelry", name: "Body Jewelry" },
        { id: "bracelets", name: "Bracelets" },
        {
          id: "brooches-lapel-pins",
          name: "Brooches & Lapel Pins",
          children: [
            { id: "brooches", name: "Brooches" },
            { id: "lapel-pins", name: "Lapel Pins" },
          ],
        },
        {
          id: "charms-pendants",
          name: "Charms & Pendants",
          children: [
            { id: "charms", name: "Charms" },
            { id: "pendants", name: "Pendants" },
          ],
        },
        { id: "dental-grills", name: "Dental Grills" },
        {
          id: "earrings",
          name: "Earrings",
          children: [
            { id: "drop-earrings", name: "Drop Earrings" },
            { id: "ear-cuffs", name: "Ear Cuffs" },
            { id: "hoop-earrings", name: "Hoop Earrings" },
            { id: "stud-earrings", name: "Stud Earrings" },
          ],
        },
        { id: "jewelry-sets", name: "Jewelry Sets" },
        {
          id: "necklaces",
          name: "Necklaces",
          children: [
            { id: "chokers", name: "Chokers" },
            { id: "layered-necklaces", name: "Layered Necklaces" },
            { id: "pendant-necklaces", name: "Pendant Necklaces" },
          ],
        },
        {
          id: "rings",
          name: "Rings",
          children: [
            { id: "engagement-rings", name: "Engagement Rings" },
            { id: "wedding-bands", name: "Wedding Bands" },
          ],
        },
        { id: "smart-watches", name: "Smart Watches" },
        {
          id: "watch-accessories",
          name: "Watch Accessories",
          children: [
            { id: "watch-bands", name: "Watch Bands" },
            { id: "watch-display-stands", name: "Watch Display Stands" },
            { id: "watch-parts-components", name: "Watch Parts & Components" },
            { id: "watch-protective-cases-covers", name: "Watch Protective Cases & Covers" },
            { id: "watch-stickers-decals", name: "Watch Stickers & Decals" },
            { id: "watch-storage-boxes-rolls", name: "Watch Storage Boxes & Rolls" },
            { id: "watch-tools", name: "Watch Tools" },
            { id: "watch-winders", name: "Watch Winders" },
          ],
        },
        { id: "watches", name: "Watches" },
      ],
    },
    {
      id: "shoe-accessories",
      name: "Shoe Accessories",
      children: [
        { id: "boot-liners", name: "Boot Liners" },
        { id: "gaiters", name: "Gaiters" },
        {
          id: "shoe-covers",
          name: "Shoe Covers",
          children: [
            { id: "boot-covers", name: "Boot Covers" },
            { id: "heel-protectors", name: "Heel Protectors" },
            { id: "toe-covers", name: "Toe Covers" },
          ],
        },
        {
          id: "shoe-grips",
          name: "Shoe Grips",
          children: [
            { id: "adhesive-grip-pads-treads", name: "Adhesive Grip Pads & Treads" },
            { id: "ice-snow-cleats", name: "Ice & Snow Cleats" },
            { id: "replacement-studs-spikes", name: "Replacement Studs & Spikes" },
            { id: "traction-sprays-rosin", name: "Traction Sprays & Rosin" },
          ],
        },
        {
          id: "shoe-inserts",
          name: "Shoe Inserts",
          children: [
            { id: "anti-slip-steps", name: "Anti Slip Steps" },
            { id: "arch-supports", name: "Arch Supports" },
            { id: "gel-pads", name: "Gel Pads" },
            {
              id: "heel-cushions",
              name: "Heel Cushions",
              children: [
                { id: "heel-grips-liners", name: "Heel Grips & Liners" },
                { id: "heel-lifts", name: "Heel Lifts" },
              ],
            },
            { id: "toe-pads", name: "Toe Pads" },
          ],
        },
        { id: "shoelaces", name: "Shoelaces" },
        { id: "spurs", name: "Spurs" },
      ],
    },
    {
      id: "shoes",
      name: "Shoes",
      children: [
        { id: "athletic-shoes", name: "Athletic Shoes" },
        {
          id: "baby-childrens-shoes",
          name: "Baby & Children's Shoes",
          children: [
            { id: "baby-childrens-athletic-shoes", name: "Baby & Children's Athletic Shoes" },
            { id: "baby-childrens-boots", name: "Baby & Children's Boots" },
            { id: "baby-childrens-sandals", name: "Baby & Children's Sandals" },
            { id: "baby-childrens-sneakers", name: "Baby & Children's Sneakers" },
            { id: "first-steps-crawlers", name: "First Steps & Crawlers" },
          ],
        },
        { id: "boots", name: "Boots" },
        { id: "flats", name: "Flats" },
        { id: "heels", name: "Heels" },
        { id: "sandals", name: "Sandals" },
        { id: "slippers", name: "Slippers" },
        { id: "sneakers", name: "Sneakers" },
      ],
    },
  ],
};

const BEAUTY_PERSONAL_CARE: CategoryNode = {
  id: "beauty-personal-care",
  name: "Beauty & Personal Care",
  children: [
    {
      id: "make-up",
      name: "Make Up",
      children: [
        {
          id: "body-makeup",
          name: "Body Makeup",
          children: [
            { id: "body-hair-glitter", name: "Body & Hair Glitter" },
            { id: "body-bronzers-tints", name: "Body Bronzers & Tints" },
            { id: "body-paint-foundation", name: "Body Paint & Foundation" },
          ],
        },
        {
          id: "cosmetic-tools",
          name: "Cosmetic Tools",
          children: [
            { id: "cosmetic-packaging-containers", name: "Cosmetic Packaging & Containers" },
            {
              id: "makeup-tools",
              name: "Makeup Tools",
              children: [
                { id: "cosmetic-pencil-sharpeners", name: "Cosmetic Pencil Sharpeners" },
                { id: "cosmetic-spatulas-mixing-tools", name: "Cosmetic Spatulas & Mixing Tools" },
                {
                  id: "double-eyelid-glue-tape",
                  name: "Double Eyelid Glue & Tape",
                  children: [
                    { id: "double-eyelid-glue-film", name: "Double Eyelid Glue & Film" },
                    { id: "double-eyelid-tapes", name: "Double Eyelid Tapes" },
                  ],
                },
                { id: "eyebrow-stencils", name: "Eyebrow Stencils" },
                { id: "eyelash-curler-refills", name: "Eyelash Curler Refills" },
                { id: "eyelash-curlers", name: "Eyelash Curlers" },
                {
                  id: "face-mirrors",
                  name: "Face Mirrors",
                  children: [
                    { id: "compact-pocket-mirrors", name: "Compact & Pocket Mirrors" },
                    { id: "handheld-mirrors", name: "Handheld Mirrors" },
                    { id: "tabletop-makeup-mirrors", name: "Tabletop Makeup Mirrors" },
                    { id: "wall-mounted-makeup-mirrors", name: "Wall-Mounted Makeup Mirrors" },
                  ],
                },
                { id: "facial-blotting-paper", name: "Facial Blotting Paper" },
                {
                  id: "false-eyelash-accessories",
                  name: "False Eyelash Accessories",
                  children: [
                    {
                      id: "false-eyelash-adhesive",
                      name: "False Eyelash Adhesive",
                      children: [
                        { id: "eyelash-extension-adhesives", name: "Eyelash Extension Adhesives" },
                        { id: "lash-lift-adhesives", name: "Lash Lift Adhesives" },
                        { id: "strip-eyelash-adhesive", name: "Strip Eyelash Adhesive" },
                      ],
                    },
                    { id: "false-eyelash-applicators", name: "False Eyelash Applicators" },
                    {
                      id: "false-eyelash-bonders-sealants",
                      name: "False Eyelash Bonders & Sealants",
                    },
                    { id: "false-eyelash-brushes-wands", name: "False Eyelash Brushes & Wands" },
                    {
                      id: "false-eyelash-cleansers-primers",
                      name: "False Eyelash Cleansers & Primers",
                    },
                    { id: "false-eyelash-pads-shields", name: "False Eyelash Pads & Shields" },
                    { id: "false-eyelash-remover", name: "False Eyelash Remover" },
                    { id: "false-eyelash-storage-cases", name: "False Eyelash Storage Cases" },
                  ],
                },
                { id: "makeup-brushes", name: "Makeup Brushes" },
                { id: "makeup-mixing-palettes", name: "Makeup Mixing Palettes" },
                { id: "makeup-powder-puffs", name: "Makeup Powder Puffs" },
                { id: "makeup-sponges", name: "Makeup Sponges" },
                {
                  id: "refillable-makeup-palettes-cases",
                  name: "Refillable Makeup Palettes & Cases",
                },
              ],
            },
            {
              id: "nail-tools",
              name: "Nail Tools",
              children: [
                { id: "cuticle-nippers", name: "Cuticle Nippers" },
                { id: "cuticle-pushers", name: "Cuticle Pushers" },
                { id: "cuticle-scissors", name: "Cuticle Scissors" },
                { id: "manicure-pedicure-spacers", name: "Manicure & Pedicure Spacers" },
                { id: "manicure-tool-sets", name: "Manicure Tool Sets" },
                { id: "nail-brushes", name: "Nail Brushes" },
                { id: "nail-buffers", name: "Nail Buffers" },
                { id: "nail-clippers", name: "Nail Clippers" },
                { id: "nail-drill-accessories", name: "Nail Drill Accessories" },
                { id: "nail-drills", name: "Nail Drills" },
                { id: "nail-dryers", name: "Nail Dryers" },
                { id: "nail-files-emery-boards", name: "Nail Files & Emery Boards" },
                { id: "nail-forms-molds", name: "Nail Forms & Molds" },
                { id: "nail-stamping-plates", name: "Nail Stamping Plates" },
              ],
            },
            {
              id: "skin-care-tools",
              name: "Skin Care Tools",
              children: [
                { id: "dermaplaning-tools", name: "Dermaplaning Tools" },
                { id: "facial-sauna-accessories", name: "Facial Sauna Accessories" },
                { id: "facial-saunas", name: "Facial Saunas" },
                { id: "foot-files", name: "Foot Files" },
                { id: "led-light-therapy-devices", name: "LED Light Therapy Devices" },
                { id: "lotion-sunscreen-applicators", name: "Lotion & Sunscreen Applicators" },
                {
                  id: "microcurrent-ems-facial-devices",
                  name: "Microcurrent & EMS Facial Devices",
                },
                { id: "pumice-stones", name: "Pumice Stones" },
                { id: "reusable-facial-cloths-pads", name: "Reusable Facial Cloths & Pads" },
                {
                  id: "skin-care-extractors",
                  name: "Skin Care Extractors",
                  children: [
                    { id: "manual-comedone-extractors", name: "Manual Comedone Extractors" },
                    { id: "pore-vacuum-extractors", name: "Pore Vacuum Extractors" },
                  ],
                },
                { id: "skin-care-rollers", name: "Skin Care Rollers" },
                { id: "skin-cleansing-brush-heads", name: "Skin Cleansing Brush Heads" },
                { id: "skin-cleansing-brushes-systems", name: "Skin Cleansing Brushes & Systems" },
              ],
            },
          ],
        },
        { id: "costume-stage-makeup", name: "Costume & Stage Makeup" },
        {
          id: "eye-makeup",
          name: "Eye Makeup",
          children: [
            { id: "eye-primers", name: "Eye Primers" },
            {
              id: "eye-shadows",
              name: "Eye Shadows",
              children: [
                { id: "eye-shadow-palettes", name: "Eye Shadow Palettes" },
                { id: "liquid-cream-eye-shadows", name: "Liquid & Cream Eye Shadows" },
                {
                  id: "loose-pigments-glitter-eye-shadows",
                  name: "Loose Pigments & Glitter Eye Shadows",
                },
                { id: "single-eyeshadows", name: "Single Eyeshadows" },
              ],
            },
            { id: "eyebrow-enhancers", name: "Eyebrow Enhancers" },
            { id: "eyeliner", name: "Eyeliner" },
            { id: "false-eyelashes", name: "False Eyelashes" },
            { id: "lash-brow-growth-treatments", name: "Lash & Brow Growth Treatments" },
            { id: "mascara-primers", name: "Mascara Primers" },
            { id: "mascaras", name: "Mascaras" },
          ],
        },
        {
          id: "face-makeup",
          name: "Face Makeup",
          children: [
            {
              id: "blushes-bronzers",
              name: "Blushes & Bronzers",
              children: [
                { id: "blushes", name: "Blushes" },
                { id: "bronzers", name: "Bronzers" },
                { id: "contour", name: "Contour" },
              ],
            },
            { id: "face-palettes", name: "Face Palettes" },
            { id: "face-powder", name: "Face Powder" },
            { id: "face-primers", name: "Face Primers" },
            {
              id: "foundations-concealers",
              name: "Foundations & Concealers",
              children: [
                { id: "bb-cc-creams", name: "BB & CC Creams" },
                { id: "color-correctors", name: "Color Correctors" },
                { id: "concealers", name: "Concealers" },
                { id: "foundations", name: "Foundations" },
              ],
            },
            { id: "highlighters-luminizers", name: "Highlighters & Luminizers" },
          ],
        },
        {
          id: "lip-makeup",
          name: "Lip Makeup",
          children: [
            { id: "lip-cheek-stains", name: "Lip & Cheek Stains" },
            { id: "lip-gloss", name: "Lip Gloss" },
            { id: "lip-liners", name: "Lip Liners" },
            { id: "lip-makeup-kits-sets", name: "Lip Makeup Kits & Sets" },
            { id: "lip-oils", name: "Lip Oils" },
            { id: "lip-plumpers", name: "Lip Plumpers" },
            { id: "lip-primers", name: "Lip Primers" },
            {
              id: "lipsticks",
              name: "Lipsticks",
              children: [
                { id: "lipstick-refills", name: "Lipstick Refills" },
                { id: "liquid-lipsticks", name: "Liquid Lipsticks" },
              ],
            },
            { id: "permanent-makeup-lip-pigments", name: "Permanent Makeup Lip Pigments" },
          ],
        },
        { id: "makeup-finishing-sprays", name: "Makeup Finishing Sprays" },
        { id: "makeup-kits-sets", name: "Makeup Kits & Sets" },
        { id: "temporary-tattoos", name: "Temporary Tattoos" },
      ],
    },
    {
      id: "skincare",
      name: "Skincare",
      children: [
        {
          id: "acne-treatments-kits",
          name: "Acne Treatments & Kits",
          children: [
            { id: "acne-patches", name: "Acne Patches" },
            { id: "acne-spot-treatments", name: "Acne Spot Treatments" },
          ],
        },
        { id: "after-sun-skin-care", name: "After-Sun Skin Care" },
        { id: "anti-aging-skin-care", name: "Anti-Aging Skin Care" },
        {
          id: "body-butters-balms",
          name: "Body Butters & Balms",
          children: [
            { id: "body-balms", name: "Body Balms" },
            { id: "body-butters", name: "Body Butters" },
          ],
        },
        { id: "body-oil", name: "Body Oil" },
        { id: "body-powder", name: "Body Powder" },
        { id: "compressed-skin-care-mask-sheets", name: "Compressed Skin Care Mask Sheets" },
        { id: "eye-creams", name: "Eye Creams" },
        { id: "face-moisturizers", name: "Face Moisturizers" },
        { id: "face-serums", name: "Face Serums" },
        { id: "facial-cleansers", name: "Facial Cleansers" },
        { id: "facial-cleansing-kits", name: "Facial Cleansing Kits" },
        { id: "facial-pore-strips", name: "Facial Pore Strips" },
        { id: "hand-creams", name: "Hand Creams" },
        {
          id: "lip-balms-treatments",
          name: "Lip Balms & Treatments",
          children: [
            { id: "lip-balms", name: "Lip Balms" },
            { id: "lip-masks", name: "Lip Masks" },
            { id: "lip-scrubs", name: "Lip Scrubs" },
            { id: "medicated-lip-treatments", name: "Medicated Lip Treatments" },
          ],
        },
        { id: "lotions-moisturizers", name: "Lotions & Moisturizers" },
        { id: "makeup-removers", name: "Makeup Removers" },
        { id: "petroleum-jelly", name: "Petroleum Jelly" },
        { id: "skin-care-kits-sets", name: "Skin Care Kits & Sets" },
        { id: "skin-care-masks-peels", name: "Skin Care Masks & Peels" },
        { id: "skin-insect-repellent", name: "Skin Insect Repellent" },
        { id: "sunscreen", name: "Sunscreen" },
        {
          id: "tanning-products",
          name: "Tanning Products",
          children: [
            { id: "self-tanner", name: "Self Tanner" },
            { id: "tan-extenders-after-sun-care", name: "Tan Extenders & After-Sun Care" },
            { id: "tan-removers", name: "Tan Removers" },
            { id: "tanning-accelerators", name: "Tanning Accelerators" },
            { id: "tanning-oil-lotions", name: "Tanning Oil & Lotions" },
            { id: "tanning-prep-primers", name: "Tanning Prep & Primers" },
          ],
        },
        {
          id: "toners-astringents",
          name: "Toners & Astringents",
          children: [
            { id: "astringents", name: "Astringents" },
            { id: "toners", name: "Toners" },
          ],
        },
        { id: "wart-removers", name: "Wart Removers" },
      ],
    },
    {
      id: "haircare",
      name: "Haircare",
      children: [
        { id: "hair-care-kits", name: "Hair Care Kits" },
        { id: "hair-color", name: "Hair Color" },
        { id: "hair-color-removers", name: "Hair Color Removers" },
        { id: "hair-coloring-accessories", name: "Hair Coloring Accessories" },
        {
          id: "hair-loss-concealers",
          name: "Hair Loss Concealers",
          children: [
            { id: "hair-building-fibers", name: "Hair Building Fibers" },
            { id: "root-concealer-powders-sticks", name: "Root Concealer Powders & Sticks" },
            { id: "root-concealer-sprays", name: "Root Concealer Sprays" },
          ],
        },
        { id: "hair-loss-treatments", name: "Hair Loss Treatments" },
        {
          id: "hair-permanents-straighteners",
          name: "Hair Permanents & Straighteners",
          children: [
            { id: "hair-perm-solutions-kits", name: "Hair Perm Solutions & Kits" },
            { id: "hair-relaxers", name: "Hair Relaxers" },
            {
              id: "hair-texturizers-softening-systems",
              name: "Hair Texturizers & Softening Systems",
            },
            { id: "keratin-smoothing-treatments", name: "Keratin & Smoothing Treatments" },
          ],
        },
        { id: "hair-shears", name: "Hair Shears" },
        {
          id: "hair-steamers-heat-caps",
          name: "Hair Steamers & Heat Caps",
          children: [
            { id: "hair-heat-caps", name: "Hair Heat Caps" },
            { id: "hair-steamers", name: "Hair Steamers" },
          ],
        },
        {
          id: "hair-styling-products",
          name: "Hair Styling Products",
          children: [
            { id: "hair-creams-lotions", name: "Hair Creams & Lotions" },
            { id: "hair-gels", name: "Hair Gels" },
            { id: "hair-mousses-foams", name: "Hair Mousses & Foams" },
            { id: "hair-pomades-waxes", name: "Hair Pomades & Waxes" },
            { id: "hair-powders", name: "Hair Powders" },
            { id: "hair-sprays", name: "Hair Sprays" },
          ],
        },
        {
          id: "hair-styling-tool-accessories",
          name: "Hair Styling Tool Accessories",
          children: [
            {
              id: "hair-curler-clips-pins",
              name: "Hair Curler Clips & Pins",
              children: [
                { id: "clips", name: "Clips" },
                {
                  id: "pins",
                  name: "Pins",
                  children: [
                    { id: "bobby-pins", name: "Bobby Pins" },
                    { id: "ripple-pins", name: "Ripple Pins" },
                    { id: "roller-pins", name: "Roller Pins" },
                  ],
                },
              ],
            },
            { id: "hair-dryer-accessories", name: "Hair Dryer Accessories" },
            { id: "hair-extension-tools-accessories", name: "Hair Extension Tools & Accessories" },
            { id: "hair-iron-accessories", name: "Hair Iron Accessories" },
            { id: "hair-spray-bottles", name: "Hair Spray Bottles" },
            { id: "hair-styling-tool-cases-pouches", name: "Hair Styling Tool Cases & Pouches" },
            { id: "heat-mats-stands", name: "Heat Mats & Stands" },
          ],
        },
        {
          id: "hair-styling-tools",
          name: "Hair Styling Tools",
          children: [
            {
              id: "combs-brushes",
              name: "Combs & Brushes",
              children: [
                { id: "combs-brushes-hair-combs", name: "Hair Combs" },
                { id: "hairbrushes-combs", name: "Hairbrushes & Combs" },
                { id: "hot-air-brushes", name: "Hot Air Brushes" },
                { id: "paddle-hairbrushes", name: "Paddle Hairbrushes" },
                { id: "round-hairbrushes", name: "Round Hairbrushes" },
                { id: "straightening-brushes", name: "Straightening Brushes" },
              ],
            },
            { id: "curling-irons", name: "Curling Irons" },
            { id: "hair-braiders", name: "Hair Braiders" },
            { id: "hair-crimpers", name: "Hair Crimpers" },
            { id: "hair-curlers", name: "Hair Curlers" },
            { id: "hair-dryers", name: "Hair Dryers" },
            { id: "hair-straighteners", name: "Hair Straighteners" },
            { id: "hair-styling-tool-sets", name: "Hair Styling Tool Sets" },
          ],
        },
        {
          id: "hair-treatments",
          name: "Hair Treatments",
          children: [
            { id: "hair-masks", name: "Hair Masks" },
            { id: "hair-oils", name: "Hair Oils" },
            { id: "hair-serums", name: "Hair Serums" },
          ],
        },
        {
          id: "shampoo-conditioner",
          name: "Shampoo & Conditioner",
          children: [
            { id: "conditioners", name: "Conditioners" },
            { id: "shampoo", name: "Shampoo" },
            { id: "shampoo-conditioner-sets", name: "Shampoo & Conditioner Sets" },
          ],
        },
      ],
    },
    {
      id: "fragrance",
      name: "Fragrance",
      children: [
        { id: "attars", name: "Attars" },
        { id: "body-mists", name: "Body Mists" },
        { id: "colognes", name: "Colognes" },
        { id: "eaux-de-parfum", name: "Eaux de Parfum" },
        { id: "eaux-de-toilette", name: "Eaux De Toilette" },
        { id: "hair-perfumes", name: "Hair Perfumes" },
        { id: "perfume-extracts", name: "Perfume Extracts" },
        { id: "perfume-oils", name: "Perfume Oils" },
        { id: "perfume-sample-discovery-sets", name: "Perfume Sample & Discovery Sets" },
        { id: "solid-perfumes", name: "Solid Perfumes" },
      ],
    },
    {
      id: "bath-and-body",
      name: "Bath and Body",
      children: [
        { id: "bar-soap", name: "Bar Soap" },
        {
          id: "bath-additives",
          name: "Bath Additives",
          children: [
            { id: "bath-melts-teas", name: "Bath Melts & Teas" },
            { id: "bath-salts-soaks", name: "Bath Salts & Soaks" },
            { id: "bubble-bath-foam", name: "Bubble Bath & Foam" },
          ],
        },
        { id: "bath-bombs", name: "Bath Bombs" },
        { id: "bath-brushes", name: "Bath Brushes" },
        {
          id: "bath-sponges-loofahs",
          name: "Bath Sponges & Loofahs",
          children: [
            { id: "exfoliating-washcloths-towels", name: "Exfoliating Washcloths & Towels" },
            { id: "soap-saver-bags-pouches", name: "Soap Saver Bags & Pouches" },
            { id: "soap-infused-sponges-buffers", name: "Soap-Infused Sponges & Buffers" },
          ],
        },
        { id: "body-scrubs-exfoliants", name: "Body Scrubs & Exfoliants" },
        { id: "body-wash", name: "Body Wash" },
        { id: "hand-sanitizers-wipes", name: "Hand Sanitizers & Wipes" },
        {
          id: "hygienic-wipes",
          name: "Hygienic Wipes",
          children: [
            { id: "body-cleansing-wipes", name: "Body Cleansing Wipes" },
            { id: "flushable-personal-wipes", name: "Flushable Personal Wipes" },
          ],
        },
        { id: "liquid-hand-soap", name: "Liquid Hand Soap" },
        { id: "powdered-hand-soap", name: "Powdered Hand Soap" },
        { id: "shower-caps", name: "Shower Caps" },
      ],
    },
    {
      id: "essential-oils",
      name: "Essential Oils",
      children: [
        { id: "essential-oil-accessories", name: "Essential Oil Accessories" },
        { id: "essential-oil-blends", name: "Essential Oil Blends" },
        { id: "essential-oil-diffusers", name: "Essential Oil Diffusers" },
        { id: "essential-oil-singles", name: "Essential Oil Singles" },
      ],
    },
    {
      id: "nail-care",
      name: "Nail Care",
      children: [
        {
          id: "cuticle-creams-oil",
          name: "Cuticle Creams & Oil",
          children: [
            { id: "cuticle-creams", name: "Cuticle Creams" },
            { id: "cuticle-oil", name: "Cuticle Oil" },
            { id: "cuticle-removers-softeners", name: "Cuticle Removers & Softeners" },
          ],
        },
        {
          id: "false-nails",
          name: "False Nails",
          children: [
            { id: "nail-tips", name: "Nail Tips" },
            { id: "nail-wraps-strips", name: "Nail Wraps & Strips" },
          ],
        },
        { id: "manicure-glue", name: "Manicure Glue" },
        {
          id: "nail-art-kits-accessories",
          name: "Nail Art Kits & Accessories",
          children: [
            { id: "nail-art-brushes-dotting-tools", name: "Nail Art Brushes & Dotting Tools" },
            { id: "nail-stickers-decals", name: "Nail Stickers & Decals" },
            { id: "nail-wraps-foils", name: "Nail Wraps & Foils" },
            { id: "rhinestones-nail-charms", name: "Rhinestones & Nail Charms" },
          ],
        },
        { id: "nail-polish-drying-drops-sprays", name: "Nail Polish Drying Drops & Sprays" },
        { id: "nail-polish-removers", name: "Nail Polish Removers" },
        { id: "nail-polish-thinners", name: "Nail Polish Thinners" },
        { id: "nail-polishes", name: "Nail Polishes" },
        { id: "nail-primers-prep-liquids", name: "Nail Primers & Prep Liquids" },
        { id: "nail-treatments", name: "Nail Treatments" },
      ],
    },
    {
      id: "supports-braces",
      name: "Supports & Braces",
      children: [
        { id: "abdominal-hernia-supports", name: "Abdominal & Hernia Supports" },
        {
          id: "ankle-supports",
          name: "Ankle Supports",
          children: [
            { id: "ankle-foot-orthoses-afos", name: "Ankle-Foot Orthoses (AFOs)" },
            { id: "medical-walking-boots", name: "Medical Walking Boots" },
          ],
        },
        {
          id: "back-braces",
          name: "Back Braces",
          children: [
            { id: "lumbar-support-belts", name: "Lumbar Support Belts" },
            { id: "sacroiliac-belts", name: "Sacroiliac Belts" },
          ],
        },
        { id: "calf-shin-supports", name: "Calf & Shin Supports" },
        { id: "elbow-supports", name: "Elbow Supports" },
        { id: "finger-thumb-braces", name: "Finger & Thumb Braces" },
        { id: "hip-groin-supports", name: "Hip & Groin Supports" },
        { id: "knee-braces", name: "Knee Braces" },
        { id: "neck-braces", name: "Neck Braces" },
        { id: "shoulder-supports", name: "Shoulder Supports" },
        { id: "wrist-braces", name: "Wrist Braces" },
      ],
    },
  ],
};

const ART_AND_CRAFTS: CategoryNode = {
  id: "art-and-crafts",
  name: "Art & Crafts",
  children: [
    { id: "paintings", name: "Paintings" },
    { id: "drawings-illustrations", name: "Drawings & Illustrations" },
    { id: "sculptures", name: "Sculptures" },
    { id: "prints-printmaking", name: "Prints & Printmaking" },
    { id: "photography", name: "Photography" },
    { id: "ceramics-pottery", name: "Ceramics & Pottery" },
    { id: "textile-fiber-art", name: "Textile & Fiber Art" },
    { id: "mixed-media-assemblage", name: "Mixed Media & Assemblage" },
    { id: "digital-art", name: "Digital Art" },
    { id: "calligraphy-lettering", name: "Calligraphy & Lettering" },
    { id: "woodwork-carving", name: "Woodwork & Carving" },
    { id: "craft-supplies", name: "Craft Supplies" },
  ],
};

export const ROOT_CATEGORY: CategoryNode = {
  id: "root",
  name: "All categories",
  children: [APPAREL_ACCESSORIES, BEAUTY_PERSONAL_CARE, ART_AND_CRAFTS],
};
