export type CategoryNode = {
  id: string;
  name: string;
  // omit entirely for a true leaf; [] means "has children, not filled in yet"
  children?: CategoryNode[];
};

export const ROOT_CATEGORY: CategoryNode = {
  id: "apparel-accessories",
  name: "Apparel & Accessories",
  children: [
    {
      id: "clothing",
      name: "Clothing",
      children: [
        { id: "activewear", name: "Activewear", children: [] },
        { id: "dresses", name: "Dresses" },
        { id: "one-pieces", name: "One-Pieces" },
        { id: "outerwear", name: "Outerwear", children: [] },
        { id: "outfit-sets", name: "Outfit Sets" },
        { id: "pants", name: "Pants", children: [] },
        { id: "shorts", name: "Shorts", children: [] },
        { id: "skirts", name: "Skirts" },
        { id: "skorts", name: "Skorts" },
        { id: "sleepwear-loungewear", name: "Sleepwear & Loungewear", children: [] },
        { id: "suits", name: "Suits", children: [] },
        { id: "swimwear", name: "Swimwear", children: [] },
        { id: "traditional-ceremonial-clothing", name: "Traditional & Ceremonial Clothing", children: [] },
        { id: "wedding-bridal-party-dresses", name: "Wedding & Bridal Party Dresses", children: [] },
        { id: "lingerie", name: "Lingerie", children: [] },
        { id: "mens-undergarments", name: "Men's Undergarments", children: [] },
        { id: "socks", name: "Socks", children: [] },
        { id: "maternity-clothing", name: "Maternity Clothing", children: [] },
        { id: "clothing-tops", name: "Clothing Tops", children: [] },
        { id: "uniforms-workwear", name: "Uniforms & Workwear", children: [] },
        { id: "baby-childrens-clothing", name: "Baby & Children's Clothing", children: [] },
      ],
    },
    {
      id: "clothing-accessories",
      name: "Clothing Accessories",
      children: [
        { id: "arm-warmers-sleeves", name: "Arm Warmers & Sleeves" },
        { id: "balaclavas", name: "Balaclavas" },
        { id: "bandanas-headties", name: "Bandanas & Headties" },
        { id: "belt-buckles", name: "Belt Buckles" },
        { id: "belts", name: "Belts" },
        { id: "bridal-accessories", name: "Bridal Accessories", children: [] },
        { id: "button-studs", name: "Button Studs" },
        { id: "collar-stays", name: "Collar Stays" },
        { id: "cufflinks", name: "Cufflinks" },
        { id: "decorative-fans", name: "Decorative Fans" },
        { id: "earmuffs", name: "Earmuffs" },
        { id: "gloves-mittens", name: "Gloves & Mittens" },
        { id: "hair-accessories", name: "Hair Accessories", children: [] },
        { id: "hand-muffs", name: "Hand Muffs" },
        { id: "handkerchiefs", name: "Handkerchiefs" },
        { id: "hats", name: "Hats", children: [] },
        { id: "headwear", name: "Headwear", children: [] },
        { id: "leg-warmers", name: "Leg Warmers" },
        { id: "leis", name: "Leis" },
        { id: "maternity-belts-support-bands", name: "Maternity Belts & Support Bands" },
        { id: "neck-gaiters", name: "Neck Gaiters" },
        { id: "neckties", name: "Neckties", children: [] },
        { id: "pinback-buttons", name: "Pinback Buttons" },
        { id: "sashes", name: "Sashes" },
        { id: "scarves-shawls", name: "Scarves & Shawls" },
        { id: "sunglasses", name: "Sunglasses" },
        { id: "suspenders", name: "Suspenders" },
        { id: "tie-clips", name: "Tie Clips" },
        { id: "traditional-clothing-accessories", name: "Traditional Clothing Accessories", children: [] },
        { id: "wristbands", name: "Wristbands", children: [] },
        { id: "fashion-face-masks", name: "Fashion Face Masks" },
        { id: "baby-childrens-clothing-accessories", name: "Baby & Children's Clothing Accessories", children: [] },
        { id: "pocket-squares", name: "Pocket Squares" },
        { id: "clothing-patches", name: "Clothing Patches" },
        { id: "detachable-collars", name: "Detachable Collars" },
      ],
    },
    {
      id: "costumes-accessories",
      name: "Costumes & Accessories",
      children: [
        { id: "costume-accessories", name: "Costume Accessories" },
        { id: "costume-shoes", name: "Costume Shoes" },
        { id: "costumes", name: "Costumes", children: [] },
        { id: "masks", name: "Masks" },
        { id: "costume-wigs", name: "Costume Wigs" },
      ],
    },
    {
      id: "handbag-wallet-accessories",
      name: "Handbag & Wallet Accessories",
      children: [
        { id: "keychains", name: "Keychains" },
        { id: "lanyards", name: "Lanyards" },
        { id: "wallet-chains", name: "Wallet Chains" },
        { id: "bag-straps-handles", name: "Bag Straps & Handles" },
        { id: "bag-bases-protectors", name: "Bag Bases & Protectors" },
        { id: "purse-hooks-hangers", name: "Purse Hooks & Hangers" },
        { id: "bag-inserts-organizers", name: "Bag Inserts & Organizers" },
        { id: "bag-charms", name: "Bag Charms" },
      ],
    },
    {
      id: "handbags-wallets-cases",
      name: "Handbags, Wallets & Cases",
      children: [
        { id: "badge-pass-holders", name: "Badge & Pass Holders", children: [] },
        { id: "business-card-cases", name: "Business Card Cases" },
        { id: "handbags", name: "Handbags", children: [] },
        { id: "wallets-money-clips", name: "Wallets & Money Clips", children: [] },
        { id: "checkbook-covers", name: "Checkbook Covers" },
      ],
    },
    {
      id: "jewelry",
      name: "Jewelry",
      children: [
        { id: "anklets", name: "Anklets" },
        { id: "body-jewelry", name: "Body Jewelry" },
        { id: "bracelets", name: "Bracelets" },
        { id: "brooches-lapel-pins", name: "Brooches & Lapel Pins", children: [] },
        { id: "charms-pendants", name: "Charms & Pendants", children: [] },
        { id: "earrings", name: "Earrings" },
        { id: "jewelry-sets", name: "Jewelry Sets" },
        { id: "necklaces", name: "Necklaces" },
        { id: "rings", name: "Rings", children: [] },
        { id: "watch-accessories", name: "Watch Accessories", children: [] },
        { id: "watches", name: "Watches" },
        { id: "smart-watches", name: "Smart Watches" },
        { id: "dental-grills", name: "Dental Grills" },
      ],
    },
    {
      id: "shoe-accessories",
      name: "Shoe Accessories",
      children: [
        { id: "boot-liners", name: "Boot Liners" },
        { id: "gaiters", name: "Gaiters" },
        { id: "shoe-covers", name: "Shoe Covers", children: [] },
        { id: "shoelaces", name: "Shoelaces" },
        { id: "spurs", name: "Spurs" },
        { id: "shoe-grips", name: "Shoe Grips", children: [] },
        { id: "shoe-inserts", name: "Shoe Inserts", children: [] },
      ],
    },
    {
      id: "shoes",
      name: "Shoes",
      children: [
        { id: "boots", name: "Boots" },
        { id: "sandals", name: "Sandals" },
        { id: "slippers", name: "Slippers" },
        { id: "athletic-shoes", name: "Athletic Shoes" },
        { id: "sneakers", name: "Sneakers" },
        { id: "flats", name: "Flats" },
        { id: "heels", name: "Heels" },
        { id: "baby-childrens-shoes", name: "Baby & Children's Shoes", children: [] },
      ],
    },
  ],
};