// The colour vocabulary shared by every place a seller picks a colour --
// OptionEditorSheet's Color option axis (variant products) and ColorSheet
// (the Necessities row). Lives here rather than in either component for the
// same reason material-options.ts does: a second export alongside a
// component export breaks Fast Refresh for that file, and this project's
// CLAUDE.md caps the accepted count of that warning at exactly 6.

// One-tap colour values, ordered by family. Multicolor leads deliberately --
// it's the one answer that applies to a print/pattern rather than a shade,
// so it shouldn't be buried under 130 named shades.
export const COLOR_PRESETS: string[] = [
  "Multicolor",
  // Black / white / grey
  "Black",
  "Jet Black",
  "Onyx",
  "Ebony",
  "Charcoal",
  "Graphite",
  "Gunmetal",
  "Slate",
  "Grey",
  "Ash Grey",
  "Steel Grey",
  "Dove Grey",
  "Pewter",
  "Smoke",
  "Stone",
  "Silver",
  "White",
  "Off White",
  "Ivory",
  "Cream",
  "Eggshell",
  "Pearl",
  "Bone",
  // Brown / tan / beige
  "Brown",
  "Chocolate",
  "Espresso",
  "Coffee",
  "Mocha",
  "Umber",
  "Sienna",
  "Mahogany",
  "Walnut",
  "Chestnut",
  "Cognac",
  "Caramel",
  "Toffee",
  "Tan",
  "Camel",
  "Nude",
  "Khaki",
  "Taupe",
  "Sand",
  "Beige",
  "Terracotta",
  // Red
  "Red",
  "Crimson",
  "Scarlet",
  "Cherry",
  "Ruby",
  "Brick Red",
  "Wine",
  "Maroon",
  "Burgundy",
  "Garnet",
  "Rust",
  // Orange
  "Orange",
  "Burnt Orange",
  "Tangerine",
  "Apricot",
  "Coral",
  "Salmon",
  "Peach",
  "Amber",
  "Copper",
  "Bronze",
  // Yellow
  "Yellow",
  "Mustard",
  "Gold",
  "Lemon",
  "Canary",
  "Honey",
  "Butter",
  "Ochre",
  // Green
  "Green",
  "Emerald",
  "Forest",
  "Hunter Green",
  "Sage",
  "Olive",
  "Moss",
  "Mint",
  "Seafoam",
  "Pistachio",
  "Lime",
  "Jade",
  "Teal",
  "Turquoise",
  // Blue
  "Sky",
  "Baby Blue",
  "Powder Blue",
  "Ice Blue",
  "Cerulean",
  "Blue",
  "Royal Blue",
  "Cobalt",
  "Denim",
  "Steel Blue",
  "Periwinkle",
  "Navy",
  "Indigo",
  // Purple
  "Violet",
  "Purple",
  "Lilac",
  "Lavender",
  "Wisteria",
  "Orchid",
  "Amethyst",
  "Plum",
  "Eggplant",
  "Grape",
  "Mauve",
  // Pink
  "Pink",
  "Blush",
  "Baby Pink",
  "Dusty Pink",
  "Bubblegum",
  "Hot Pink",
  "Rose",
  "Magenta",
  "Fuchsia",
  // Metallic / other
  "Rose Gold",
  "Champagne",
];

// Real swatches for Color — a dot per name reads as "this app understands
// color" where a plain text row reads generic. Multicolor gets a gradient.
export const COLOR_SWATCHES: Record<string, string> = {
  Black: "#111111",
  "Jet Black": "#060606",
  Onyx: "#0F0F0F",
  Ebony: "#3D2B1F",
  Charcoal: "#36454F",
  Graphite: "#4B4B4B",
  Gunmetal: "#2A3439",
  Slate: "#708090",
  Grey: "#9CA3AF",
  "Ash Grey": "#B2BEB5",
  "Steel Grey": "#71797E",
  "Dove Grey": "#6E6E6E",
  Pewter: "#96A8A1",
  Smoke: "#848884",
  Stone: "#928E85",
  Silver: "#C0C0C0",
  White: "#FFFFFF",
  "Off White": "#F5F5F0",
  Ivory: "#FFFFF0",
  Cream: "#F5EEDC",
  Eggshell: "#F0EAD6",
  Pearl: "#EAE0C8",
  Bone: "#E3DAC9",
  Brown: "#7B4B2A",
  Chocolate: "#4E2A1E",
  Espresso: "#3C2415",
  Coffee: "#4B3621",
  Mocha: "#6F4E37",
  Umber: "#635147",
  Sienna: "#A0522D",
  Mahogany: "#4A2511",
  Walnut: "#5C4033",
  Chestnut: "#954535",
  Cognac: "#9A463D",
  Caramel: "#C68E3F",
  Toffee: "#7C4A2D",
  Tan: "#D2B48C",
  Camel: "#C19A6B",
  Nude: "#E3BFA0",
  Khaki: "#BDB76B",
  Taupe: "#8B7D6B",
  Sand: "#C2B280",
  Beige: "#D9C7AA",
  Terracotta: "#E2725B",
  Red: "#DC2626",
  Crimson: "#DC143C",
  Scarlet: "#FF2400",
  Cherry: "#9E1B32",
  Ruby: "#9B111E",
  "Brick Red": "#B04A3B",
  Wine: "#722F37",
  Maroon: "#800000",
  Burgundy: "#6D071A",
  Garnet: "#733635",
  Rust: "#B7410E",
  Orange: "#F97316",
  "Burnt Orange": "#CC5500",
  Tangerine: "#F28500",
  Apricot: "#FBCEB1",
  Coral: "#FF7F50",
  Salmon: "#FA8072",
  Peach: "#FFCBA4",
  Amber: "#FFBF00",
  Copper: "#B87333",
  Bronze: "#CD7F32",
  Yellow: "#FACC15",
  Mustard: "#E1AD01",
  Gold: "#D4AF37",
  Lemon: "#FFF44F",
  Canary: "#FFFF99",
  Honey: "#E8A33D",
  Butter: "#FFF1A8",
  Ochre: "#CC7722",
  Green: "#16A34A",
  Emerald: "#10B981",
  Forest: "#228B22",
  "Hunter Green": "#355E3B",
  Sage: "#9CAF88",
  Olive: "#6B8E23",
  Moss: "#8A9A5B",
  Mint: "#6EE7B7",
  Seafoam: "#9FE2BF",
  Pistachio: "#93C572",
  Lime: "#A8C33B",
  Jade: "#00A86B",
  Teal: "#14B8A6",
  Turquoise: "#40E0D0",
  Sky: "#87CEEB",
  "Baby Blue": "#89CFF0",
  "Powder Blue": "#B0E0E6",
  "Ice Blue": "#D6ECF0",
  Cerulean: "#007BA7",
  Blue: "#2563EB",
  "Royal Blue": "#4169E1",
  Cobalt: "#0047AB",
  Denim: "#1560BD",
  "Steel Blue": "#4682B4",
  Periwinkle: "#CCCCFF",
  Navy: "#1E3A8A",
  Indigo: "#4338CA",
  Violet: "#7C3AED",
  Purple: "#9333EA",
  Lilac: "#C8A2C8",
  Lavender: "#C4B5FD",
  Wisteria: "#C9A0DC",
  Orchid: "#DA70D6",
  Amethyst: "#9966CC",
  Plum: "#8E4585",
  Eggplant: "#614051",
  Grape: "#6F2DA8",
  Mauve: "#B784A7",
  Pink: "#EC4899",
  Blush: "#F7C6C7",
  "Baby Pink": "#F4C2C2",
  "Dusty Pink": "#D8A7B1",
  Bubblegum: "#FFC1CC",
  "Hot Pink": "#FF69B4",
  Rose: "#E0708C",
  Magenta: "#C2185B",
  Fuchsia: "#D946EF",
  "Rose Gold": "#B76E79",
  Champagne: "#F7E7CE",
};

export const MULTICOLOR_GRADIENT =
  "conic-gradient(from 0deg, #DC2626, #F97316, #FACC15, #16A34A, #2563EB, #9333EA, #DC2626)";

// Every named shade has a flat hex; anything without one (Multicolor) falls
// back to the gradient, so a swatch is never rendered blank.
export function colorSwatchStyle(name: string): string {
  return COLOR_SWATCHES[name] ?? MULTICOLOR_GRADIENT;
}

// Broad, everyday color words a seller is likely to type (blue, brown,
// purple...) mapped to every preset shade that actually belongs to that
// family -- named shades rarely contain the family word in their own string
// (e.g. "Cobalt" has no "blue" in it, "Lilac" has no "purple" in it), so a
// plain substring search alone would never surface them. One shade can sit
// in more than one family on purpose (Fuchsia reads as both pink and
// purple, Rust as both red and orange) -- these are fashion groupings, not
// a strict color-wheel partition.
const COLOR_FAMILIES: Record<string, string[]> = {
  black: ["Black", "Jet Black", "Onyx", "Ebony", "Charcoal"],
  white: ["White", "Off White", "Ivory", "Cream", "Eggshell", "Pearl", "Bone"],
  grey: [
    "Grey",
    "Charcoal",
    "Graphite",
    "Gunmetal",
    "Slate",
    "Ash Grey",
    "Steel Grey",
    "Dove Grey",
    "Silver",
    "Pewter",
    "Smoke",
    "Stone",
  ],
  gray: [
    "Grey",
    "Charcoal",
    "Graphite",
    "Gunmetal",
    "Slate",
    "Ash Grey",
    "Steel Grey",
    "Dove Grey",
    "Silver",
    "Pewter",
    "Smoke",
    "Stone",
  ],
  brown: [
    "Brown",
    "Chocolate",
    "Espresso",
    "Coffee",
    "Mocha",
    "Umber",
    "Sienna",
    "Mahogany",
    "Walnut",
    "Chestnut",
    "Cognac",
    "Caramel",
    "Toffee",
    "Tan",
    "Camel",
    "Taupe",
  ],
  tan: ["Tan", "Camel", "Khaki", "Taupe", "Sand", "Beige", "Nude"],
  beige: ["Beige", "Sand", "Cream", "Nude", "Taupe", "Ivory"],
  red: [
    "Red",
    "Crimson",
    "Scarlet",
    "Cherry",
    "Ruby",
    "Brick Red",
    "Wine",
    "Maroon",
    "Burgundy",
    "Garnet",
    "Rust",
  ],
  orange: [
    "Orange",
    "Burnt Orange",
    "Tangerine",
    "Apricot",
    "Coral",
    "Peach",
    "Amber",
    "Rust",
    "Copper",
    "Terracotta",
  ],
  yellow: ["Yellow", "Mustard", "Gold", "Lemon", "Canary", "Honey", "Butter", "Ochre"],
  green: [
    "Green",
    "Emerald",
    "Forest",
    "Hunter Green",
    "Sage",
    "Olive",
    "Moss",
    "Mint",
    "Seafoam",
    "Pistachio",
    "Lime",
    "Jade",
  ],
  teal: ["Teal", "Turquoise", "Jade", "Seafoam"],
  blue: [
    "Sky",
    "Baby Blue",
    "Powder Blue",
    "Ice Blue",
    "Cerulean",
    "Blue",
    "Royal Blue",
    "Cobalt",
    "Denim",
    "Steel Blue",
    "Periwinkle",
    "Navy",
    "Indigo",
    "Turquoise",
    "Teal",
  ],
  navy: ["Navy", "Indigo", "Royal Blue"],
  purple: [
    "Violet",
    "Purple",
    "Lilac",
    "Lavender",
    "Wisteria",
    "Orchid",
    "Amethyst",
    "Plum",
    "Eggplant",
    "Grape",
    "Mauve",
    "Fuchsia",
  ],
  violet: ["Violet", "Purple", "Lavender", "Lilac", "Wisteria", "Amethyst"],
  pink: [
    "Pink",
    "Blush",
    "Baby Pink",
    "Dusty Pink",
    "Bubblegum",
    "Hot Pink",
    "Rose",
    "Magenta",
    "Fuchsia",
    "Salmon",
    "Mauve",
  ],
  gold: ["Gold", "Bronze", "Copper", "Rose Gold", "Champagne", "Mustard"],
  silver: ["Silver", "Pewter", "Steel Grey", "Gunmetal"],
  metallic: ["Gold", "Silver", "Bronze", "Copper", "Rose Gold", "Champagne", "Pewter", "Gunmetal"],
};

// Only expands into a whole family once the query is a real word fragment --
// under 3 characters, most family keys contain it as a substring (e.g. "b"
// is inside "black", "blue", AND "brown"), which would explode the list
// instead of narrowing it. startsWith in both directions (not includes)
// covers a partial type-ahead ("pur" -> "purple") and a plural/longer form
// ("blues"/"purples" -> "blue"/"purple") without that false-positive.
export function colorFamilyMembers(q: string): Set<string> | null {
  if (q.length < 3) return null;
  let members: Set<string> | null = null;
  for (const [family, list] of Object.entries(COLOR_FAMILIES)) {
    // family.startsWith(q) is the type-ahead direction ("pur" -> "purple").
    // q === family + "s" is a plural ("blues" -> "blue"). q's words
    // including family whole is a multi-word descriptive query ("navy
    // blue", "light blue" -> "blue") -- checked as a WHOLE word, not
    // q.startsWith(family)/q.includes(family), because either of those
    // would also fire on any preset name that happens to start with or
    // contain a short family key (e.g. "tangerine" contains "tan"),
    // pulling in that whole unrelated family right as the seller finishes
    // typing an exact match.
    if (family.startsWith(q) || q === family + "s" || q.split(/\s+/).includes(family)) {
      members ??= new Set();
      for (const v of list) members.add(v);
    }
  }
  return members;
}
