import type { ThemeSpec } from "./theme-spec";
import type { ThemeId } from "./types";

// The data-driven half of the catalogue. Palettes are grounded in the
// ui-ux-pro-max colour set (192 product palettes) and the faces are drawn
// from its 74 curated pairings, mapped onto the families fonts.ts already
// carries. Each entry is the whole theme: see theme-spec.ts for why these are
// data and the original eight are components.
//
// Every accent is the one colour that carries the storefront — tile tints,
// promo card, avatar cluster and the hero rule are all derived from it, so a
// theme cannot drift out of tune with itself.
export const THEME_SPECS: ThemeSpec[] = [
  // ── lavender / violet ────────────────────────────────────────────────────
  {
    id: "lilac-hour",
    name: "Lilac Hour",
    eyebrow: "SOFT · ROMANTIC · LIGHT",
    description: "Pale lavender and a low sun — for labels that feel like a quiet morning.",
    demoBrand: "Lilac Hour",
    moods: ["soft", "romantic", "pastel", "dreamy", "feminine"],
    bg: "#FAF5FF",
    ink: "#2E1065",
    accent: "#7C3AED",
    heading: "cormorant",
    body: "montserrat",
    heroAlign: "center",
    heroSize: 46,
    rule: true,
    decor: { kind: "glow", at: "50% 0%" },
    copy: {
      eyebrow: "New season, softly",
      sub: "Pieces made for slow mornings.",
      followers: "in the lilac club",
      footer: "Worn this week",
      promoEyebrow: "Just landed",
      promoTitle: "The lavender edit is live",
      promoCta: "Explore",
    },
    collections: ["New In", "Dresses", "Knitwear", "Accessories"],
    counts: [14, 22, 11, 18],
    products: ["Lilac Slip", "Cloud Cardigan", "Dawn Scarf", "Petal Bag"],
    prices: [42000, 58000, 15000, 36000],
  },
  {
    id: "orchid",
    name: "Orchid",
    eyebrow: "DEEP · LUSH · NOCTURNAL",
    description: "Violet-black with an orchid glow, for labels that come alive after dark.",
    demoBrand: "Orchid",
    moods: ["moody", "nocturnal", "sultry", "dramatic", "luxe"],
    bg: "#140A1F",
    ink: "#F3EAFF",
    accent: "#A78BFA",
    heading: "prata",
    body: "jost",
    heroAlign: "left",
    heroSize: 42,
    decor: { kind: "orbs" },
    copy: {
      eyebrow: "After hours",
      sub: "Nightwear for people who don't sleep early.",
      followers: "in the orchid house",
      footer: "Seen out tonight",
      promoEyebrow: "Limited run",
      promoTitle: "Forty pieces, then it's gone",
      promoCta: "Shop now",
    },
    collections: ["Night", "Silk", "Outerwear", "Jewellery"],
    counts: [9, 16, 12, 21],
    products: ["Orchid Robe", "Velvet Slip", "Night Coat", "Petal Cuff"],
    prices: [88000, 64000, 145000, 29000],
  },
  {
    id: "wisteria",
    name: "Wisteria",
    eyebrow: "AIRY · GENTLE · EDITORIAL",
    description: "Washed violet on white — an unhurried, gallery-quiet storefront.",
    demoBrand: "Wisteria",
    moods: ["airy", "gentle", "editorial", "minimal", "quiet"],
    bg: "#F5F3FF",
    ink: "#1E1B4B",
    accent: "#8B5CF6",
    heading: "instrumentSerif",
    body: "workSans",
    heroAlign: "center",
    heroSize: 48,
    decor: { kind: "wash" },
    copy: {
      eyebrow: "Spring selects",
      sub: "Light layers, long wear.",
      followers: "following the vine",
      footer: "In the wild",
      promoEyebrow: "This week",
      promoTitle: "Everything light, all in one place",
      promoCta: "See the edit",
    },
    collections: ["Layers", "Linen", "Shoes", "Objects"],
    counts: [17, 13, 9, 7],
    products: ["Wisteria Shirt", "Air Trouser", "Vine Sandal", "Stem Vase"],
    prices: [38000, 46000, 52000, 19000],
  },
  {
    id: "amethyst",
    name: "Amethyst",
    eyebrow: "JEWELLED · DARK · PRECISE",
    description: "Near-black cut with amethyst, for pieces that catch the light.",
    demoBrand: "Amethyst",
    moods: ["jewelled", "dark", "luxury", "precise", "glamorous"],
    bg: "#0B0713",
    ink: "#EDE6FA",
    accent: "#C4B5FD",
    heading: "cinzel",
    body: "raleway",
    heroAlign: "center",
    heroSize: 36,
    heroUppercase: true,
    rule: true,
    decor: { kind: "glow" },
    copy: {
      eyebrow: "Cut and set",
      sub: "Fine pieces, few of each.",
      followers: "in the vault",
      footer: "Worn by the few",
      promoEyebrow: "By appointment",
      promoTitle: "The stone collection opens Friday",
      promoCta: "Reserve",
    },
    collections: ["Rings", "Chains", "Stones", "Archive"],
    counts: [24, 18, 11, 6],
    products: ["Amethyst Band", "Fine Chain", "Cut Stone", "Archive Cuff"],
    prices: [120000, 78000, 165000, 210000],
  },
  {
    id: "periwinkle",
    name: "Periwinkle",
    eyebrow: "CLEAN · MODERN · CALM",
    description: "Blue-lilac on paper white, structured and unfussy.",
    demoBrand: "Periwinkle",
    moods: ["clean", "modern", "minimal", "calm", "structured"],
    bg: "#F0F1FF",
    ink: "#1E1B4B",
    accent: "#6366F1",
    heading: "syne",
    body: "plusJakarta",
    heroAlign: "left",
    heroSize: 40,
    decor: { kind: "glow" },
    copy: {
      eyebrow: "Built simply",
      sub: "Everyday shapes, considered.",
      followers: "shop here",
      footer: "Out in the world",
      promoEyebrow: "Restocked",
      promoTitle: "The core pieces are back in every size",
      promoCta: "Shop core",
    },
    collections: ["Core", "Tops", "Denim", "Bags"],
    counts: [26, 31, 14, 12],
    products: ["Core Tee", "Straight Jean", "Day Bag", "Knit Vest"],
    prices: [18000, 54000, 44000, 32000],
  },
  {
    id: "mauve-studio",
    name: "Mauve Studio",
    eyebrow: "MUTED · STUDIO · TACTILE",
    description: "Dusty mauve and warm grey — a working studio, not a showroom.",
    demoBrand: "Mauve Studio",
    moods: ["muted", "earthy", "artisanal", "tactile", "understated"],
    bg: "#F7F2F7",
    ink: "#3B2C3B",
    accent: "#9D6B9D",
    heading: "fraunces",
    body: "karla",
    heroAlign: "left",
    heroSize: 40,
    decor: { kind: "none" },
    copy: {
      eyebrow: "Made in studio",
      sub: "Small batches, made to order.",
      followers: "in the studio",
      footer: "Made and worn",
      promoEyebrow: "Batch two",
      promoTitle: "Twelve pieces cut this month",
      promoCta: "See batch",
    },
    collections: ["Batch", "Knits", "Trousers", "Remnants"],
    counts: [12, 9, 15, 5],
    products: ["Studio Smock", "Mauve Knit", "Wide Trouser", "Offcut Tote"],
    prices: [49000, 62000, 57000, 21000],
  },

  // ── pink / rose ──────────────────────────────────────────────────────────
  {
    id: "blush",
    name: "Blush",
    eyebrow: "SWEET · BRIGHT · PLAYFUL",
    description: "Baby pink with a hot-pink pulse — cheerful and impossible to miss.",
    demoBrand: "Blush",
    moods: ["sweet", "playful", "bright", "girly", "fun"],
    bg: "#FDF2F8",
    ink: "#500724",
    accent: "#EC4899",
    heading: "calistoga",
    body: "quicksand",
    heroAlign: "center",
    heroSize: 44,
    decor: { kind: "orbs" },
    copy: {
      eyebrow: "Everything pink",
      sub: "For people who don't do subtle.",
      followers: "in the blush club",
      footer: "Spotted wearing",
      promoEyebrow: "Weekend only",
      promoTitle: "Pink on pink, while it lasts",
      promoCta: "Shop pink",
    },
    collections: ["All Pink", "Tops", "Sets", "Hair"],
    counts: [28, 19, 13, 24],
    products: ["Blush Set", "Sugar Tee", "Rose Clip", "Candy Bag"],
    prices: [39000, 16000, 7000, 34000],
  },
  {
    id: "rosewater",
    name: "Rosewater",
    eyebrow: "DELICATE · CLEAN · FRESH",
    description: "The palest rose, kept almost white — quiet but never cold.",
    demoBrand: "Rosewater",
    moods: ["delicate", "clean", "fresh", "soft", "gentle"],
    bg: "#FFF5F7",
    ink: "#4C0519",
    accent: "#F43F5E",
    heading: "cormorantInfant",
    body: "figtree",
    heroAlign: "center",
    heroSize: 48,
    rule: true,
    decor: { kind: "wash" },
    copy: {
      eyebrow: "Softly does it",
      sub: "Fabric first, always.",
      followers: "keep coming back",
      footer: "Worn daily",
      promoEyebrow: "New fabric",
      promoTitle: "Washed cotton, cut three ways",
      promoCta: "Feel it",
    },
    collections: ["Cotton", "Sleep", "Basics", "Home"],
    counts: [21, 14, 33, 10],
    products: ["Rose Camisole", "Wash Robe", "Daily Tee", "Linen Throw"],
    prices: [27000, 51000, 15000, 43000],
  },
  {
    id: "fuchsia-night",
    name: "Fuchsia Night",
    eyebrow: "LOUD · ELECTRIC · AFTER DARK",
    description: "Black soaked in fuchsia — built for drops that trend by morning.",
    demoBrand: "Fuchsia",
    moods: ["loud", "electric", "nightlife", "bold", "streetwear"],
    bg: "#12060E",
    ink: "#FFE9F5",
    accent: "#FF4FA3",
    heading: "unbounded",
    body: "spaceGrotesk",
    heroAlign: "left",
    heroSize: 40,
    heroUppercase: true,
    decor: { kind: "glow" },
    copy: {
      eyebrow: "Drop is live",
      sub: "If you're reading this, it's already moving.",
      followers: "waiting on the drop",
      footer: "Out tonight",
      promoEyebrow: "Live now",
      promoTitle: "Sixty minutes on the clock",
      promoCta: "Get it",
    },
    collections: ["The Drop", "Tees", "Outer", "Caps"],
    counts: [8, 26, 14, 19],
    products: ["Neon Hoodie", "Drop Tee", "Night Cap", "Glow Short"],
    prices: [72000, 24000, 14000, 31000],
  },
  {
    id: "peony",
    name: "Peony",
    eyebrow: "RICH · FEMININE · FORMAL",
    description: "Deep rose on ivory, for occasion pieces and the people who wear them.",
    demoBrand: "Peony",
    moods: ["romantic", "formal", "elegant", "feminine", "luxurious"],
    bg: "#FFF1F5",
    ink: "#4A0B2A",
    accent: "#BE185D",
    heading: "playfairSc",
    body: "montserrat",
    heroAlign: "center",
    heroSize: 40,
    rule: true,
    decor: { kind: "glow", at: "50% 0%" },
    copy: {
      eyebrow: "For the occasion",
      sub: "Dressing for the room you're walking into.",
      followers: "dress with us",
      footer: "Worn to weddings",
      promoEyebrow: "Season of events",
      promoTitle: "Made-to-measure is open again",
      promoCta: "Book a fitting",
    },
    collections: ["Occasion", "Gowns", "Tailoring", "Veils"],
    counts: [11, 8, 13, 5],
    products: ["Peony Gown", "Silk Sash", "Fitted Jacket", "Bloom Clutch"],
    prices: [185000, 32000, 128000, 47000],
  },
  {
    id: "bubblegum",
    name: "Bubblegum",
    eyebrow: "FUN · YOUNG · UNSERIOUS",
    description: "Candy pink and rounded type — a storefront that smiles first.",
    demoBrand: "Bubblegum",
    moods: ["fun", "playful", "youthful", "cute", "colourful"],
    bg: "#FFF0F6",
    ink: "#4A1030",
    accent: "#FF6FB5",
    heading: "righteous",
    body: "nunito",
    heroAlign: "center",
    heroSize: 42,
    decor: { kind: "orbs" },
    copy: {
      eyebrow: "Don't overthink it",
      sub: "Clothes that are fun to put on.",
      followers: "chew on this",
      footer: "Wearing it out",
      promoEyebrow: "Two for one",
      promoTitle: "Grab two, pay for one, all weekend",
      promoCta: "Grab both",
    },
    collections: ["Fun Stuff", "Tees", "Socks", "Stickers"],
    counts: [30, 22, 17, 41],
    products: ["Gum Tee", "Pop Socks", "Sweet Cap", "Candy Pin"],
    prices: [14000, 6000, 12000, 3500],
  },
  {
    id: "dusty-rose",
    name: "Dusty Rose",
    eyebrow: "WARM · VINTAGE · SOFT",
    description: "Faded rose and old paper, like a well-kept archive.",
    demoBrand: "Dusty Rose",
    moods: ["vintage", "warm", "nostalgic", "soft", "romantic"],
    bg: "#F6EDEA",
    ink: "#432521",
    accent: "#B76E79",
    heading: "libreBaskerville",
    body: "lora",
    heroAlign: "left",
    heroSize: 38,
    decor: { kind: "none" },
    copy: {
      eyebrow: "From the archive",
      sub: "Found, mended, worn again.",
      followers: "in the archive",
      footer: "Given a second life",
      promoEyebrow: "Archive release",
      promoTitle: "Eleven found pieces, each one only once",
      promoCta: "See the find",
    },
    collections: ["Archive", "Vintage", "Mended", "Lace"],
    counts: [11, 16, 7, 9],
    products: ["Rose Blouse", "Mended Coat", "Lace Slip", "Old Belt"],
    prices: [36000, 92000, 41000, 18000],
  },

  // ── the two named requests ───────────────────────────────────────────────
  {
    id: "black-gold",
    name: "Black & Gold",
    eyebrow: "OPULENT · FORMAL · EXACT",
    description: "True black struck with gold — the most formal room in the catalogue.",
    demoBrand: "Maison Or",
    moods: ["opulent", "luxury", "formal", "glamorous", "elegant"],
    bg: "#050505",
    ink: "#F5EFE0",
    accent: "#D4AF37",
    heading: "cinzel",
    body: "tenorSans",
    heroAlign: "center",
    heroSize: 36,
    heroUppercase: true,
    rule: true,
    decor: { kind: "glow", at: "50% 0%" },
    copy: {
      eyebrow: "By invitation",
      sub: "Made slowly, in small numbers.",
      followers: "in the maison",
      footer: "Worn to the room",
      promoEyebrow: "Private view",
      promoTitle: "The gold collection opens to members first",
      promoCta: "Enter",
    },
    collections: ["Maison", "Tailoring", "Gold", "Archive"],
    counts: [9, 14, 11, 6],
    products: ["Gold Thread Coat", "Black Tailored Set", "Signet Ring", "Silk Pocket"],
    prices: [320000, 240000, 96000, 28000],
  },
  {
    id: "black-red",
    name: "Black & Red",
    eyebrow: "SHARP · AGGRESSIVE · BOLD",
    description: "Pure black and a true, full-strength red — loud without saying much.",
    demoBrand: "Redline",
    moods: ["bold", "edgy", "aggressive", "streetwear", "loud"],
    // A real red, not a crimson. This used to be #E11D48 (Tailwind rose-600),
    // which sits at 350° and reads pink-leaning beside an actual red. #FF1A1A
    // is 0°, and bright enough to clear AA on black by itself, so
    // readableAccent leaves it alone instead of lifting it toward pink.
    bg: "#050505",
    ink: "#FFFFFF",
    accent: "#FF1A1A",
    heading: "archivoBlack",
    body: "barlowCondensed",
    heroAlign: "left",
    heroSize: 44,
    heroUppercase: true,
    // A red bloom rather than the corner brackets, so the red is in the
    // hero itself and not only in the tiles below it.
    decor: { kind: "glow", at: "15% 0%" },
    copy: {
      eyebrow: "No apologies",
      sub: "Built to be seen from across the street.",
      followers: "run with us",
      footer: "On the street",
      promoEyebrow: "Cut short",
      promoTitle: "This run ends when it ends",
      promoCta: "Take it",
    },
    collections: ["Redline", "Outer", "Denim", "Boots"],
    counts: [12, 18, 15, 9],
    products: ["Red Stripe Jacket", "Blackout Denim", "Line Tee", "Heavy Boot"],
    prices: [118000, 74000, 22000, 136000],
  },

  // ── wine ─────────────────────────────────────────────────────────────────
  // Red, but grown up: neither is a pure red on a pure ground (that's Black &
  // Red). Bordeaux keeps its accent bright enough to glow on near-black —
  // a true claret there would vanish into the ground — and lets
  // readableAccent lift it further for text. Merlot is the daylight version:
  // blush linen, with the deep wine doing the talking.
  {
    id: "bordeaux",
    name: "Bordeaux",
    eyebrow: "DEEP · VELVET · CANDLELIT",
    description: "Wine-dark claret and candlelight — for labels with a slow, rich voice.",
    demoBrand: "Maison Bordeaux",
    moods: ["romantic", "moody", "luxurious", "sultry", "elegant"],
    bg: "#170A0D",
    ink: "#F5E9E6",
    accent: "#B23A52",
    heading: "playfair",
    body: "raleway",
    heroAlign: "center",
    heroSize: 44,
    rule: true,
    decor: { kind: "glow", at: "50% 0%" },
    copy: {
      eyebrow: "Poured slowly",
      sub: "Evening pieces with a long finish.",
      followers: "at the table",
      footer: "Worn by candlelight",
      promoEyebrow: "Private cellar",
      promoTitle: "The velvet edit, uncorked",
      promoCta: "Discover",
    },
    collections: ["Evening", "Velvet", "Tailoring", "Jewellery"],
    counts: [12, 9, 15, 20],
    products: ["Claret Slip Dress", "Velvet Blazer", "Cellar Coat", "Garnet Drop"],
    prices: [96000, 128000, 175000, 34000],
  },
  {
    id: "merlot",
    name: "Merlot",
    eyebrow: "WARM · ROMANTIC · GROWN-UP",
    description: "Blush linen and a deep merlot wine — soft on the eye, sure of itself.",
    demoBrand: "Merlot",
    moods: ["romantic", "warm", "sophisticated", "elegant", "soft"],
    bg: "#F8EFEC",
    ink: "#3B0D18",
    accent: "#7E1F35",
    heading: "libreBodoni",
    body: "figtree",
    heroAlign: "left",
    heroSize: 42,
    decor: { kind: "wash" },
    copy: {
      eyebrow: "The merlot season",
      sub: "Soft tailoring, deep colour.",
      followers: "raising a glass",
      footer: "Worn this weekend",
      promoEyebrow: "Just in",
      promoTitle: "Merlot knits are back",
      promoCta: "Shop the edit",
    },
    collections: ["New In", "Knitwear", "Dresses", "Bags"],
    counts: [18, 14, 21, 10],
    products: ["Merlot Knit", "Wrap Dress", "Linen Trouser", "Wine Tote"],
    prices: [48000, 72000, 39000, 44000],
  },
  // The third wine, and the only one where the wine is the ground itself:
  // Bordeaux is claret on near-black and Merlot is wine on blush, so
  // Burgundy fills the whole page with the colour and lets champagne do the
  // accenting. A burgundy accent here would vanish into its own background.
  {
    id: "burgundy",
    name: "Burgundy",
    eyebrow: "RICH · AUTUMNAL · TAILORED",
    description: "A whole storefront in deep burgundy, finished in champagne.",
    demoBrand: "Maison Burgundy",
    moods: ["rich", "autumnal", "tailored", "classic", "luxurious"],
    bg: "#4A0D1E",
    ink: "#F7EDE4",
    accent: "#E3C08D",
    heading: "spectral",
    body: "jost",
    heroAlign: "center",
    heroSize: 42,
    rule: true,
    decor: { kind: "orbs" },
    copy: {
      eyebrow: "The burgundy season",
      sub: "Deep colour, cut close.",
      followers: "in the house",
      footer: "Worn into autumn",
      promoEyebrow: "New in",
      promoTitle: "The burgundy wool edit",
      promoCta: "Shop the edit",
    },
    collections: ["New In", "Tailoring", "Knitwear", "Leather"],
    counts: [16, 12, 19, 8],
    products: ["Burgundy Wool Coat", "Pleated Trouser", "Cable Knit", "Leather Loafer"],
    prices: [165000, 58000, 62000, 88000],
  },

  // ── warm / earth ─────────────────────────────────────────────────────────
  {
    id: "terracotta",
    name: "Terracotta",
    eyebrow: "EARTHY · HANDMADE · WARM",
    description: "Fired clay and warm sand — for makers who work with their hands.",
    demoBrand: "Terracotta",
    moods: ["earthy", "handmade", "warm", "artisanal", "rustic"],
    bg: "#FBF1EA",
    ink: "#4A2413",
    accent: "#C2410C",
    heading: "yeseva",
    body: "karla",
    heroAlign: "left",
    heroSize: 40,
    decor: { kind: "wash" },
    copy: {
      eyebrow: "Fired and finished",
      sub: "Every piece leaves a thumbprint.",
      followers: "at the kiln",
      footer: "In people's homes",
      promoEyebrow: "Kiln open",
      promoTitle: "This week's firing is ready to collect",
      promoCta: "Collect",
    },
    collections: ["Ceramics", "Vessels", "Tiles", "Seconds"],
    counts: [19, 12, 8, 14],
    products: ["Clay Vase", "Sand Bowl", "Fired Mug", "Second Plate"],
    prices: [26000, 19000, 11000, 8000],
  },
  {
    id: "saffron",
    name: "Saffron",
    eyebrow: "GOLDEN · SUNLIT · GENEROUS",
    description: "Warm cream and saffron, like late afternoon indoors.",
    demoBrand: "Saffron",
    moods: ["golden", "sunny", "warm", "cheerful", "vibrant"],
    bg: "#FFF8E7",
    ink: "#422A06",
    accent: "#D97706",
    heading: "dmSerif",
    body: "workSans",
    heroAlign: "center",
    heroSize: 44,
    rule: true,
    decor: { kind: "glow", at: "50% 0%" },
    copy: {
      eyebrow: "Colour first",
      sub: "Dyed in small lots, never twice the same.",
      followers: "wear the colour",
      footer: "Out in the sun",
      promoEyebrow: "Dye lot 04",
      promoTitle: "This shade will not be repeated",
      promoCta: "Take a piece",
    },
    collections: ["Dyed", "Scarves", "Wraps", "Lots"],
    counts: [16, 21, 13, 6],
    products: ["Saffron Wrap", "Lot 04 Scarf", "Sun Shirt", "Dye Sample"],
    prices: [44000, 29000, 37000, 9000],
  },
  {
    id: "clay",
    name: "Clay",
    eyebrow: "NEUTRAL · GROUNDED · PLAIN",
    description: "Unbleached and unhurried, with nothing shouting for attention.",
    demoBrand: "Clay",
    moods: ["neutral", "minimal", "grounded", "understated", "calm"],
    bg: "#F4EDE6",
    ink: "#3A2E23",
    accent: "#A16207",
    heading: "vollkorn",
    body: "manrope",
    heroAlign: "left",
    heroSize: 38,
    decor: { kind: "none" },
    copy: {
      eyebrow: "Nothing added",
      sub: "Undyed cloth, plain cuts.",
      followers: "keep it plain",
      footer: "Worn in",
      promoEyebrow: "Undyed",
      promoTitle: "Raw cotton, cut four ways",
      promoCta: "See the cuts",
    },
    collections: ["Undyed", "Shirts", "Trousers", "Cloth"],
    counts: [13, 17, 14, 5],
    products: ["Raw Shirt", "Plain Trouser", "Clay Smock", "Cloth Metre"],
    prices: [34000, 41000, 47000, 12000],
  },
  {
    id: "amber-dusk",
    name: "Amber Dusk",
    eyebrow: "MOODY · WARM · LOW-LIT",
    description: "Dark brown lit by amber — the last hour before closing.",
    demoBrand: "Amber Dusk",
    moods: ["moody", "warm", "intimate", "cosy", "atmospheric"],
    bg: "#120B04",
    ink: "#F7EBD9",
    accent: "#F59E0B",
    heading: "marcellus",
    body: "spectral",
    heroAlign: "center",
    heroSize: 40,
    rule: true,
    decor: { kind: "glow" },
    copy: {
      eyebrow: "Open late",
      sub: "Come by before the lights go down.",
      followers: "come by often",
      footer: "Carried home",
      promoEyebrow: "Closing hour",
      promoTitle: "Last pieces go out tonight",
      promoCta: "Come by",
    },
    collections: ["Evening", "Leather", "Wool", "Last Call"],
    counts: [10, 15, 12, 7],
    products: ["Amber Jacket", "Dusk Bag", "Wool Scarf", "Last Pair"],
    prices: [156000, 88000, 33000, 64000],
  },
  {
    id: "copper",
    name: "Copper",
    eyebrow: "METALLIC · INDUSTRIAL · AGED",
    description: "Dark metal and oxidised copper, for hard-wearing things.",
    demoBrand: "Copperworks",
    moods: ["industrial", "rugged", "metallic", "utilitarian", "worn-in"],
    bg: "#14100C",
    ink: "#EFE4D8",
    accent: "#B87333",
    heading: "oswald",
    body: "archivo",
    heroAlign: "left",
    heroSize: 42,
    heroUppercase: true,
    decor: { kind: "brackets" },
    copy: {
      eyebrow: "Built to last",
      sub: "Repairs are free, forever.",
      followers: "on the workbench",
      footer: "Still going",
      promoEyebrow: "Workshop",
      promoTitle: "Bring anything back and we'll fix it",
      promoCta: "Book a repair",
    },
    collections: ["Workwear", "Canvas", "Hardware", "Repairs"],
    counts: [18, 11, 23, 9],
    products: ["Copper Rivet Jacket", "Canvas Apron", "Work Trouser", "Repair Kit"],
    prices: [132000, 46000, 68000, 15000],
  },

  // ── ember / brown ────────────────────────────────────────────────────────
  // The orange here is deliberately dulled — fired clay, not a traffic cone
  // (Terracotta and Tangerine Pop already cover the loud end). Kiln sits on a
  // warm parchment with near-black ink, a calm, bookish pairing; Hearth is
  // the same ember after dark. The browns are grounds you can actually see
  // are brown, unlike Copper's near-black: Espresso is a real chocolate
  // ground, Walnut a toasted tan.
  {
    id: "kiln",
    name: "Kiln",
    eyebrow: "WARM · THOUGHTFUL · HANDMADE",
    description: "Warm parchment and a kiln-fired orange — calm, human, quietly confident.",
    demoBrand: "Kiln Studio",
    moods: ["warm", "thoughtful", "handmade", "cosy", "calm"],
    bg: "#F4F0E8",
    ink: "#1F1B16",
    accent: "#C96442",
    heading: "newsreader",
    body: "dmSans",
    heroAlign: "left",
    heroSize: 44,
    rule: true,
    decor: { kind: "glow", at: "85% 0%" },
    copy: {
      eyebrow: "Made by hand",
      sub: "Everyday pieces, thought through.",
      followers: "people who get it",
      footer: "Worn and loved",
      promoEyebrow: "Small batch",
      promoTitle: "Fresh out of the kiln",
      promoCta: "Take a look",
    },
    collections: ["Everyday", "Linen", "Outerwear", "Accessories"],
    counts: [24, 13, 9, 17],
    products: ["Kiln Overshirt", "Linen Wide Leg", "Field Jacket", "Clay Tote"],
    prices: [54000, 46000, 98000, 31000],
  },
  {
    id: "hearth",
    name: "Hearth",
    eyebrow: "COSY · GLOWING · CRAFTED",
    description: "Warm charcoal lit by an ember orange — like a fire in the next room.",
    demoBrand: "Hearth",
    moods: ["cosy", "warm", "intimate", "crafted", "homely"],
    bg: "#1C1815",
    ink: "#F3ECE3",
    accent: "#D97757",
    heading: "fraunces",
    body: "workSans",
    heroAlign: "left",
    heroSize: 42,
    decor: { kind: "glow", at: "20% 0%" },
    copy: {
      eyebrow: "Pull up a chair",
      sub: "Knitwear and layers for long evenings.",
      followers: "around the fire",
      footer: "Worn at home",
      promoEyebrow: "Cold snap",
      promoTitle: "Heavy knits, warm prices",
      promoCta: "Warm up",
    },
    collections: ["Knitwear", "Layers", "Loungewear", "Scarves"],
    counts: [19, 16, 11, 14],
    products: ["Ember Knit", "Hearth Cardigan", "Fireside Set", "Ash Scarf"],
    prices: [62000, 74000, 55000, 18000],
  },
  {
    id: "espresso",
    name: "Espresso",
    eyebrow: "RICH · GROUNDED · CLASSIC",
    description: "Deep espresso and toasted caramel — for leather, denim and things built to last.",
    demoBrand: "Espresso & Co.",
    moods: ["rich", "classic", "grounded", "masculine", "rugged"],
    bg: "#211610",
    ink: "#F2E7DA",
    accent: "#C8955F",
    heading: "dmSerif",
    body: "manrope",
    heroAlign: "center",
    heroSize: 44,
    rule: true,
    decor: { kind: "glow", at: "50% 0%" },
    copy: {
      eyebrow: "Built to last",
      sub: "Leather, denim and good wool.",
      followers: "regulars",
      footer: "Broken in",
      promoEyebrow: "From the workshop",
      promoTitle: "Hand-stitched leather, restocked",
      promoCta: "Shop leather",
    },
    collections: ["Leather", "Denim", "Outerwear", "Boots"],
    counts: [16, 22, 12, 9],
    products: ["Saddle Bag", "Selvedge Jean", "Waxed Jacket", "Chelsea Boot"],
    prices: [68000, 52000, 135000, 89000],
  },
  {
    id: "walnut",
    name: "Walnut",
    eyebrow: "NATURAL · WARM · UNHURRIED",
    description: "Toasted tan and walnut brown — earthy, tactile and easy to live with.",
    demoBrand: "Walnut",
    moods: ["natural", "warm", "earthy", "relaxed", "tactile"],
    bg: "#EFE5D8",
    ink: "#2F2118",
    accent: "#7A4B2A",
    heading: "merriweather",
    body: "plusJakarta",
    heroAlign: "left",
    heroSize: 40,
    decor: { kind: "wash" },
    copy: {
      eyebrow: "Natural fibres",
      sub: "Honest colour, made to be lived in.",
      followers: "who like it simple",
      footer: "Lived in",
      promoEyebrow: "New arrivals",
      promoTitle: "The walnut collection",
      promoCta: "Explore",
    },
    collections: ["New In", "Knitwear", "Trousers", "Leather Goods"],
    counts: [15, 18, 12, 10],
    products: ["Walnut Knit", "Pleated Trouser", "Suede Loafer", "Oak Belt"],
    prices: [51000, 43000, 76000, 21000],
  },

  // ── green / teal ─────────────────────────────────────────────────────────
  {
    id: "sage",
    name: "Sage",
    eyebrow: "HERBAL · QUIET · NATURAL",
    description: "Soft green on bone — restful, with nothing sharp in it.",
    demoBrand: "Sage",
    moods: ["natural", "calm", "organic", "quiet", "earthy"],
    bg: "#F1F5F0",
    ink: "#26332A",
    accent: "#6B8F71",
    heading: "ebGaramond",
    body: "lexend",
    heroAlign: "center",
    heroSize: 44,
    rule: true,
    decor: { kind: "wash" },
    copy: {
      eyebrow: "Grown well",
      sub: "Plant-dyed, air-dried, nothing rushed.",
      followers: "growing with us",
      footer: "Worn outdoors",
      promoEyebrow: "Harvest",
      promoTitle: "This season's dye plants are in the cloth",
      promoCta: "See the batch",
    },
    collections: ["Plant Dyed", "Linen", "Garden", "Seeds"],
    counts: [15, 19, 8, 12],
    products: ["Sage Shirt", "Garden Apron", "Leaf Wrap", "Seed Pouch"],
    prices: [39000, 28000, 34000, 6000],
  },
  {
    id: "eucalyptus",
    name: "Eucalyptus",
    eyebrow: "FRESH · CLINICAL · CLEAN",
    description: "Cool green and white, precise and easy to read.",
    demoBrand: "Eucalypt",
    moods: ["fresh", "clean", "minimal", "crisp", "modern"],
    bg: "#EEF5F1",
    ink: "#12302A",
    accent: "#059669",
    heading: "sora",
    body: "dmSans",
    heroAlign: "left",
    heroSize: 40,
    decor: { kind: "glow" },
    copy: {
      eyebrow: "Straightforward",
      sub: "Clear sizing, honest fabric, no games.",
      followers: "shop with us",
      footer: "In rotation",
      promoEyebrow: "Restock",
      promoTitle: "Every size back in stock this morning",
      promoCta: "Shop all",
    },
    collections: ["Everyday", "Tops", "Bottoms", "Sets"],
    counts: [34, 27, 22, 16],
    products: ["Clean Tee", "Cool Trouser", "Fresh Set", "Green Sock"],
    prices: [17000, 45000, 62000, 7000],
  },
  {
    id: "deep-teal",
    name: "Deep Teal",
    eyebrow: "DEEP · MARINE · STILL",
    description: "Near-black teal with a bright edge — cold water, deep end.",
    demoBrand: "Deep Teal",
    moods: ["moody", "marine", "cool", "still", "sophisticated"],
    bg: "#041214",
    ink: "#E2F6F5",
    accent: "#14B8A6",
    heading: "libreCaslon",
    body: "publicSans",
    heroAlign: "center",
    heroSize: 40,
    rule: true,
    decor: { kind: "glow" },
    copy: {
      eyebrow: "Below the surface",
      sub: "Weatherproof, tested properly.",
      followers: "dive in with us",
      footer: "Taken out",
      promoEyebrow: "Tested",
      promoTitle: "Six months in the water, still going",
      promoCta: "See the test",
    },
    collections: ["Marine", "Shells", "Knits", "Kit"],
    counts: [13, 9, 17, 11],
    products: ["Teal Shell", "Deep Knit", "Water Short", "Dry Bag"],
    prices: [148000, 72000, 38000, 44000],
  },
  {
    id: "mint",
    name: "Mint",
    eyebrow: "CRISP · LIGHT · YOUNG",
    description: "Pale mint and near-white, bright without being loud.",
    demoBrand: "Mint",
    moods: ["crisp", "fresh", "youthful", "light", "airy"],
    bg: "#F0FDF7",
    ink: "#052E20",
    accent: "#10B981",
    heading: "outfit",
    body: "figtree",
    heroAlign: "center",
    heroSize: 42,
    decor: { kind: "orbs" },
    copy: {
      eyebrow: "Keep it light",
      sub: "Summer weights, all year.",
      followers: "in the mint club",
      footer: "Worn all summer",
      promoEyebrow: "Summer weights",
      promoTitle: "Everything under 200 grams",
      promoCta: "Shop light",
    },
    collections: ["Light", "Shorts", "Tanks", "Swim"],
    counts: [23, 18, 26, 14],
    products: ["Mint Tank", "Light Short", "Cool Swim", "Air Shirt"],
    prices: [15000, 24000, 33000, 29000],
  },
  {
    id: "forest-ink",
    name: "Forest Ink",
    eyebrow: "DENSE · SHADED · SLOW",
    description: "Blackened green under canopy light — heavy cloth, long wear.",
    demoBrand: "Forest Ink",
    moods: ["moody", "rugged", "outdoorsy", "dark", "earthy"],
    bg: "#071009",
    ink: "#E6F2E8",
    accent: "#4ADE80",
    heading: "newsreader",
    body: "sourceSerif",
    heroAlign: "left",
    heroSize: 40,
    decor: { kind: "glow", at: "20% 0%" },
    copy: {
      eyebrow: "Under canopy",
      sub: "Heavy cloth for long walks.",
      followers: "walking with us",
      footer: "Taken out",
      promoEyebrow: "Cold months",
      promoTitle: "The heavy weights are back on the rail",
      promoCta: "Go heavy",
    },
    collections: ["Heavy", "Waxed", "Wool", "Packs"],
    counts: [11, 8, 16, 10],
    products: ["Waxed Coat", "Forest Wool", "Trail Trouser", "Canvas Pack"],
    prices: [168000, 84000, 59000, 77000],
  },

  // ── blue ─────────────────────────────────────────────────────────────────
  {
    id: "cobalt",
    name: "Cobalt",
    eyebrow: "CONFIDENT · GRAPHIC · DIRECT",
    description: "Hard cobalt on cool white — plainly commercial, and good at it.",
    demoBrand: "Cobalt",
    moods: ["bold", "modern", "graphic", "confident", "clean"],
    bg: "#F2F5FF",
    ink: "#0B1A4A",
    accent: "#2563EB",
    heading: "lexendMega",
    body: "plusJakarta",
    heroAlign: "left",
    heroSize: 38,
    heroUppercase: true,
    decor: { kind: "glow" },
    copy: {
      eyebrow: "Straight to it",
      sub: "Good clothes, clear prices.",
      followers: "shop here weekly",
      footer: "In rotation",
      promoEyebrow: "Price drop",
      promoTitle: "Twenty pieces down, no code needed",
      promoCta: "Shop sale",
    },
    collections: ["Sale", "New", "Staples", "Bulk"],
    counts: [20, 29, 35, 12],
    products: ["Cobalt Tee", "Blue Jean", "Staple Shirt", "Three Pack"],
    prices: [13000, 49000, 26000, 34000],
  },
  {
    id: "midnight",
    name: "Midnight",
    eyebrow: "COOL · NOCTURNAL · REFINED",
    description: "Ink blue with a cold moon on it — restrained and late.",
    demoBrand: "Midnight",
    moods: ["nocturnal", "refined", "cool", "moody", "sophisticated"],
    bg: "#04070F",
    ink: "#E4ECFA",
    accent: "#60A5FA",
    heading: "italiana",
    body: "jost",
    heroAlign: "center",
    heroSize: 42,
    rule: true,
    decor: { kind: "glow" },
    copy: {
      eyebrow: "Late edition",
      sub: "Published at midnight, every month.",
      followers: "read us monthly",
      footer: "Out in the city",
      promoEyebrow: "Issue 12",
      promoTitle: "This month's edition is online now",
      promoCta: "Read it",
    },
    collections: ["Editions", "Coats", "Shirting", "Prints"],
    counts: [12, 10, 18, 15],
    products: ["Midnight Coat", "Ink Shirt", "Moon Print", "Issue Tote"],
    prices: [176000, 54000, 21000, 26000],
  },
  {
    id: "ice",
    name: "Ice",
    eyebrow: "PALE · SHARP · MINIMAL",
    description: "Nearly white with a cold blue edge — clinical in a good way.",
    demoBrand: "Ice",
    moods: ["minimal", "clinical", "crisp", "technical", "cool"],
    bg: "#F4F9FF",
    ink: "#0C2233",
    accent: "#0EA5E9",
    heading: "syncopate",
    body: "manrope",
    heroAlign: "center",
    heroSize: 30,
    heroUppercase: true,
    decor: { kind: "wash" },
    copy: {
      eyebrow: "Cold storage",
      sub: "Technical pieces, plainly described.",
      followers: "on the list",
      footer: "Field tested",
      promoEyebrow: "Spec sheet",
      promoTitle: "Every fabric weight is published now",
      promoCta: "Read specs",
    },
    collections: ["Technical", "Shells", "Base", "Spec"],
    counts: [14, 9, 21, 6],
    products: ["Ice Shell", "Base Layer", "Cold Glove", "Spec Cap"],
    prices: [162000, 43000, 28000, 19000],
  },
  {
    id: "navy-linen",
    name: "Navy Linen",
    eyebrow: "CLASSIC · COASTAL · EASY",
    description: "Deep navy on oatmeal — the most wearable thing in the catalogue.",
    demoBrand: "Navy Linen",
    moods: ["classic", "coastal", "casual", "timeless", "relaxed"],
    bg: "#EDF0F5",
    ink: "#12203A",
    accent: "#1E3A8A",
    heading: "crimson",
    body: "karla",
    heroAlign: "left",
    heroSize: 42,
    decor: { kind: "none" },
    copy: {
      eyebrow: "Hot months",
      sub: "Linen that only gets better creased.",
      followers: "summer with us",
      footer: "Packed and worn",
      promoEyebrow: "Linen season",
      promoTitle: "The whole linen run, one weekend only",
      promoCta: "Shop linen",
    },
    collections: ["Linen", "Shirts", "Shorts", "Holiday"],
    counts: [22, 25, 17, 13],
    products: ["Navy Linen Shirt", "Oat Short", "Beach Trouser", "Sun Hat"],
    prices: [47000, 31000, 52000, 18000],
  },

  // ── neutral / editorial ──────────────────────────────────────────────────
  {
    id: "bone",
    name: "Bone",
    eyebrow: "PALE · DRY · UNDERSTATED",
    description: "Bone white and stone grey, with the volume all the way down.",
    demoBrand: "Bone",
    moods: ["minimal", "understated", "quiet", "neutral", "calm"],
    bg: "#F7F5F0",
    ink: "#292524",
    accent: "#57534E",
    heading: "cardo",
    body: "workSans",
    heroAlign: "center",
    heroSize: 44,
    rule: true,
    decor: { kind: "none" },
    copy: {
      eyebrow: "Very little",
      sub: "Six pieces. That's the whole shop.",
      followers: "keep it small",
      footer: "Worn every day",
      promoEyebrow: "Six pieces",
      promoTitle: "We stopped making anything else",
      promoCta: "See all six",
    },
    collections: ["The Six", "Tops", "Bottoms", "One Coat"],
    counts: [6, 2, 3, 1],
    products: ["Bone Shirt", "Stone Trouser", "One Coat", "Plain Tee"],
    prices: [52000, 68000, 190000, 24000],
  },
  {
    id: "graphite",
    name: "Graphite",
    eyebrow: "COLD · TECHNICAL · EXACT",
    description: "Charcoal on charcoal with a steel edge — measured, not moody.",
    demoBrand: "Graphite",
    moods: ["technical", "cold", "precise", "industrial", "minimal"],
    bg: "#0C0C0D",
    ink: "#E8E9EB",
    accent: "#9CA3AF",
    heading: "staatliches",
    body: "spaceGrotesk",
    heroAlign: "left",
    heroSize: 44,
    heroUppercase: true,
    decor: { kind: "brackets" },
    copy: {
      eyebrow: "Measured",
      sub: "Every garment listed to the gram.",
      followers: "follow the numbers",
      footer: "In service",
      promoEyebrow: "Full spec",
      promoTitle: "Weights and measures now on every listing",
      promoCta: "Inspect",
    },
    collections: ["Spec", "Shells", "Frames", "Tools"],
    counts: [17, 12, 8, 14],
    products: ["Graphite Shell", "Steel Frame", "Grey Trouser", "Field Tool"],
    prices: [139000, 64000, 58000, 23000],
  },
  {
    id: "oat",
    name: "Oat",
    eyebrow: "SOFT · HOMELY · PLAIN",
    description: "Warm oat and brown — the most comfortable room in the house.",
    demoBrand: "Oat",
    moods: ["cosy", "homely", "soft", "comfortable", "warm"],
    bg: "#F6F2EA",
    ink: "#3B3226",
    accent: "#8B7355",
    heading: "zillaSlab",
    body: "nunito",
    heroAlign: "left",
    heroSize: 40,
    decor: { kind: "wash" },
    copy: {
      eyebrow: "Stay in",
      sub: "Made for the hours nobody sees.",
      followers: "stay in with us",
      footer: "Lived in",
      promoEyebrow: "Warm things",
      promoTitle: "Everything soft, in one place",
      promoCta: "Get cosy",
    },
    collections: ["Soft", "Knits", "Home", "Sleep"],
    counts: [24, 19, 15, 11],
    products: ["Oat Jumper", "House Sock", "Soft Throw", "Sleep Set"],
    prices: [56000, 9000, 48000, 42000],
  },
  {
    id: "porcelain",
    name: "Porcelain",
    eyebrow: "STARK · GALLERY · PRECISE",
    description: "Gallery white with true black type — the product and nothing else.",
    demoBrand: "Porcelain",
    moods: ["minimal", "gallery", "stark", "precise", "editorial"],
    bg: "#FBFBF9",
    ink: "#1C1917",
    accent: "#1C1917",
    heading: "bodoni",
    body: "tenorSans",
    heroAlign: "center",
    heroSize: 46,
    rule: true,
    decor: { kind: "none" },
    copy: {
      eyebrow: "Nothing in the way",
      sub: "White walls, good light, that's it.",
      followers: "visit often",
      footer: "Taken home",
      promoEyebrow: "Now showing",
      promoTitle: "This month's hang is up",
      promoCta: "View",
    },
    collections: ["Showing", "Editions", "Prints", "Objects"],
    counts: [8, 12, 16, 9],
    products: ["White Shirt", "Black Trouser", "Edition Print", "Clay Object"],
    prices: [64000, 78000, 35000, 27000],
  },
  {
    id: "charcoal-rose",
    name: "Charcoal Rose",
    eyebrow: "MOODY · SOFT · CONTRARY",
    description: "Near-black warmed by a dusty rose — soft edges on a hard ground.",
    demoBrand: "Charcoal Rose",
    moods: ["moody", "romantic", "soft", "dramatic", "contrary"],
    bg: "#131011",
    ink: "#F2E9EA",
    accent: "#E8B4B8",
    heading: "abril",
    body: "raleway",
    heroAlign: "center",
    heroSize: 40,
    rule: true,
    decor: { kind: "glow", at: "50% 0%" },
    copy: {
      eyebrow: "Soft on dark",
      sub: "Gentle things, seriously made.",
      followers: "in the quiet room",
      footer: "Worn close",
      promoEyebrow: "New in",
      promoTitle: "Rose on charcoal, the whole run",
      promoCta: "See it",
    },
    collections: ["New In", "Silk", "Knits", "Small"],
    counts: [13, 10, 18, 22],
    products: ["Rose Slip", "Charcoal Knit", "Soft Glove", "Ash Cuff"],
    prices: [68000, 72000, 26000, 19000],
  },

  // ── statement ────────────────────────────────────────────────────────────
  {
    id: "electric-lime",
    name: "Electric Lime",
    eyebrow: "HARSH · SPORT · HIGH-VIS",
    description: "Blackout with a high-vis lime cut through it. Impossible to ignore.",
    demoBrand: "Voltage",
    moods: ["sporty", "bold", "high-energy", "edgy", "loud"],
    bg: "#0A0F02",
    ink: "#EFFCD8",
    accent: "#BEF264",
    heading: "anton",
    body: "barlowCondensed",
    heroAlign: "left",
    heroSize: 46,
    heroUppercase: true,
    decor: { kind: "glow" },
    copy: {
      eyebrow: "Full send",
      sub: "Made for people who move fast.",
      followers: "move with us",
      footer: "Out running",
      promoEyebrow: "Race week",
      promoTitle: "Kit drops Thursday, gone by Friday",
      promoCta: "Get kitted",
    },
    collections: ["Kit", "Run", "Layers", "Reflective"],
    counts: [16, 21, 13, 9],
    products: ["Volt Vest", "Run Short", "Hi-Vis Tee", "Night Band"],
    prices: [58000, 32000, 21000, 8000],
  },
  {
    id: "tangerine-pop",
    name: "Tangerine Pop",
    eyebrow: "BRIGHT · CHEERFUL · LOUD",
    description: "Warm white and full-strength tangerine — a storefront in a good mood.",
    demoBrand: "Tangerine",
    moods: ["bright", "cheerful", "playful", "colourful", "energetic"],
    bg: "#FFF4EC",
    ink: "#4A1D02",
    accent: "#FB923C",
    heading: "bricolage",
    body: "rubik",
    heroAlign: "center",
    heroSize: 42,
    decor: { kind: "orbs" },
    copy: {
      eyebrow: "Turn it up",
      sub: "Colour, and plenty of it.",
      followers: "in a good mood",
      footer: "Worn loudly",
      promoEyebrow: "Colour week",
      promoTitle: "Every bright thing, marked down",
      promoCta: "Go bright",
    },
    collections: ["Bright", "Prints", "Tees", "Bags"],
    counts: [27, 19, 24, 15],
    products: ["Tangerine Tee", "Pop Print", "Sun Bag", "Bright Cap"],
    prices: [16000, 23000, 38000, 13000],
  },
];

const SPEC_BY_ID = new Map<string, ThemeSpec>(THEME_SPECS.map((s) => [s.id, s]));

/** The spec for a theme id, falling back to the first one. The fallback is
 *  what FullPreview's default case renders for a slug with no component and
 *  no spec — a storefront in the wrong theme beats a blank screen. */
export function specForTheme(id: ThemeId): ThemeSpec {
  return SPEC_BY_ID.get(id) ?? THEME_SPECS[0];
}

export function hasSpec(id: string): boolean {
  return SPEC_BY_ID.has(id);
}
