/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhereDidYouHearAboutUsRouteImport } from './routes/where-did-you-hear-about-us'
import { Route as WhatsYourStyleRouteImport } from './routes/whats-your-style'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SwitchingRolesRouteImport } from './routes/switching-roles'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetUpStoreRouteImport } from './routes/set-up-store'
import { Route as SellerTypeRouteImport } from './routes/seller-type'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviousIndexRouteImport } from './routes/previous-index'
import { Route as PasskeyRouteImport } from './routes/passkey'
import { Route as OfflineVideosRouteImport } from './routes/offline-videos'
import { Route as NoAccountRouteImport } from './routes/no-account'
import { Route as NameYourStoreRouteImport } from './routes/name-your-store'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FindYourFitRouteImport } from './routes/find-your-fit'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as CreatePasswordRouteImport } from './routes/create-password'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChooseUsernameRouteImport } from './routes/choose-username'
import { Route as BecomeACuratorRouteImport } from './routes/become-a-curator'
import { Route as BecomeACreatorRouteImport } from './routes/become-a-creator'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as StoreThemeRouteImport } from './routes/store.theme'
import { Route as StoreProductsRouteImport } from './routes/store.products'
import { Route as StoreOrdersRouteImport } from './routes/store.orders'
import { Route as StoreGrowthRouteImport } from './routes/store.growth'
import { Route as StoreGetTheWebappRouteImport } from './routes/store.get-the-webapp'
import { Route as StoreFinanceRouteImport } from './routes/store.finance'
import { Route as StoreDiscountsRouteImport } from './routes/store.discounts'
import { Route as StoreCustomersRouteImport } from './routes/store.customers'
import { Route as StoreContentRouteImport } from './routes/store.content'
import { Route as StoreCollectionsRouteImport } from './routes/store.collections'
import { Route as StoreProfileStoreUsernameRouteImport } from './routes/store-profile.$storeUsername'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as CreateVideoEditorRouteImport } from './routes/create.video-editor'
import { Route as CreatePhotoEditorRouteImport } from './routes/create.photo-editor'
import { Route as CreateDraftsRouteImport } from './routes/create.drafts'
import { Route as CreateAfterShotRouteImport } from './routes/create.after-shot'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiSoundsRouteImport } from './routes/api.sounds'
import { Route as ApiSoundFileRouteImport } from './routes/api.sound-file'
import { Route as ApiPostsRouteImport } from './routes/api.posts'
import { Route as CreateAfterShotIndexRouteImport } from './routes/create.after-shot.index'
import { Route as StoreProductsUploadRouteImport } from './routes/store.products_.upload'
import { Route as StoreProductsNewcomerRouteImport } from './routes/store.products_.newcomer'
import { Route as StoreProductsNewRouteImport } from './routes/store.products_.new'
import { Route as StoreProductsIdRouteImport } from './routes/store.products_.$id'
import { Route as StoreLocationsNewRouteImport } from './routes/store.locations_.new'
import { Route as StoreCollectionsNewRouteImport } from './routes/store.collections_.new'
import { Route as StoreCollectionsIdRouteImport } from './routes/store.collections_.$id'
import { Route as CreateAfterShotStudioRouteImport } from './routes/create.after-shot.studio'
import { Route as CreateAfterShotPublishRouteImport } from './routes/create.after-shot.publish'
import { Route as ApiSupportMessagesReplyRouteImport } from './routes/api.support-messages.reply'
import { Route as ApiStorePayoutRouteImport } from './routes/api.store.payout'
import { Route as ApiStoreThemeUploadImageRouteImport } from './routes/api.store-theme.upload-image'
import { Route as ApiShopifyInstallRouteImport } from './routes/api.shopify.install'
import { Route as ApiShopifyCallbackRouteImport } from './routes/api.shopify.callback'
import { Route as ApiShipbubblePingRouteImport } from './routes/api.shipbubble.ping'
import { Route as ApiProductsUploadImageRouteImport } from './routes/api.products.upload-image'
import { Route as ApiInstagramConnectRouteImport } from './routes/api.instagram.connect'
import { Route as ApiInstagramCallbackRouteImport } from './routes/api.instagram.callback'
import { Route as ApiImportStatusRouteImport } from './routes/api.import.status'
import { Route as ApiImportStartRouteImport } from './routes/api.import.start'
import { Route as ApiImportCsvRouteImport } from './routes/api.import.csv'
import { Route as ApiBumpaConnectRouteImport } from './routes/api.bumpa.connect'
import { Route as ApiAccountDeleteRouteImport } from './routes/api.account.delete'

const WhereDidYouHearAboutUsRoute = WhereDidYouHearAboutUsRouteImport.update({
  id: '/where-did-you-hear-about-us',
  path: '/where-did-you-hear-about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsYourStyleRoute = WhatsYourStyleRouteImport.update({
  id: '/whats-your-style',
  path: '/whats-your-style',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchingRolesRoute = SwitchingRolesRouteImport.update({
  id: '/switching-roles',
  path: '/switching-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetUpStoreRoute = SetUpStoreRouteImport.update({
  id: '/set-up-store',
  path: '/set-up-store',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerTypeRoute = SellerTypeRouteImport.update({
  id: '/seller-type',
  path: '/seller-type',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviousIndexRoute = PreviousIndexRouteImport.update({
  id: '/previous-index',
  path: '/previous-index',
  getParentRoute: () => rootRouteImport,
} as any)
const PasskeyRoute = PasskeyRouteImport.update({
  id: '/passkey',
  path: '/passkey',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineVideosRoute = OfflineVideosRouteImport.update({
  id: '/offline-videos',
  path: '/offline-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccountRoute = NoAccountRouteImport.update({
  id: '/no-account',
  path: '/no-account',
  getParentRoute: () => rootRouteImport,
} as any)
const NameYourStoreRoute = NameYourStoreRouteImport.update({
  id: '/name-your-store',
  path: '/name-your-store',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FindYourFitRoute = FindYourFitRouteImport.update({
  id: '/find-your-fit',
  path: '/find-your-fit',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePasswordRoute = CreatePasswordRouteImport.update({
  id: '/create-password',
  path: '/create-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseUsernameRoute = ChooseUsernameRouteImport.update({
  id: '/choose-username',
  path: '/choose-username',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeACuratorRoute = BecomeACuratorRouteImport.update({
  id: '/become-a-curator',
  path: '/become-a-curator',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeACreatorRoute = BecomeACreatorRouteImport.update({
  id: '/become-a-creator',
  path: '/become-a-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const StoreThemeRoute = StoreThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductsRoute = StoreProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrdersRoute = StoreOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StoreRoute,
} as any)
const StoreGrowthRoute = StoreGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => StoreRoute,
} as any)
const StoreGetTheWebappRoute = StoreGetTheWebappRouteImport.update({
  id: '/get-the-webapp',
  path: '/get-the-webapp',
  getParentRoute: () => StoreRoute,
} as any)
const StoreFinanceRoute = StoreFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => StoreRoute,
} as any)
const StoreDiscountsRoute = StoreDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCustomersRoute = StoreCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContentRoute = StoreContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCollectionsRoute = StoreCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProfileStoreUsernameRoute =
  StoreProfileStoreUsernameRouteImport.update({
    id: '/store-profile/$storeUsername',
    path: '/store-profile/$storeUsername',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateVideoEditorRoute = CreateVideoEditorRouteImport.update({
  id: '/video-editor',
  path: '/video-editor',
  getParentRoute: () => CreateRoute,
} as any)
const CreatePhotoEditorRoute = CreatePhotoEditorRouteImport.update({
  id: '/photo-editor',
  path: '/photo-editor',
  getParentRoute: () => CreateRoute,
} as any)
const CreateDraftsRoute = CreateDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => CreateRoute,
} as any)
const CreateAfterShotRoute = CreateAfterShotRouteImport.update({
  id: '/after-shot',
  path: '/after-shot',
  getParentRoute: () => CreateRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundsRoute = ApiSoundsRouteImport.update({
  id: '/api/sounds',
  path: '/api/sounds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundFileRoute = ApiSoundFileRouteImport.update({
  id: '/api/sound-file',
  path: '/api/sound-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAfterShotIndexRoute = CreateAfterShotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateAfterShotRoute,
} as any)
const StoreProductsUploadRoute = StoreProductsUploadRouteImport.update({
  id: '/products_/upload',
  path: '/products/upload',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductsNewcomerRoute = StoreProductsNewcomerRouteImport.update({
  id: '/products_/newcomer',
  path: '/products/newcomer',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductsNewRoute = StoreProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductsIdRoute = StoreProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => StoreRoute,
} as any)
const StoreLocationsNewRoute = StoreLocationsNewRouteImport.update({
  id: '/locations_/new',
  path: '/locations/new',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCollectionsNewRoute = StoreCollectionsNewRouteImport.update({
  id: '/collections_/new',
  path: '/collections/new',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCollectionsIdRoute = StoreCollectionsIdRouteImport.update({
  id: '/collections_/$id',
  path: '/collections/$id',
  getParentRoute: () => StoreRoute,
} as any)
const CreateAfterShotStudioRoute = CreateAfterShotStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => CreateAfterShotRoute,
} as any)
const CreateAfterShotPublishRoute = CreateAfterShotPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => CreateAfterShotRoute,
} as any)
const ApiSupportMessagesReplyRoute = ApiSupportMessagesReplyRouteImport.update({
  id: '/api/support-messages/reply',
  path: '/api/support-messages/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorePayoutRoute = ApiStorePayoutRouteImport.update({
  id: '/api/store/payout',
  path: '/api/store/payout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreThemeUploadImageRoute =
  ApiStoreThemeUploadImageRouteImport.update({
    id: '/api/store-theme/upload-image',
    path: '/api/store-theme/upload-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyInstallRoute = ApiShopifyInstallRouteImport.update({
  id: '/api/shopify/install',
  path: '/api/shopify/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifyCallbackRoute = ApiShopifyCallbackRouteImport.update({
  id: '/api/shopify/callback',
  path: '/api/shopify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShipbubblePingRoute = ApiShipbubblePingRouteImport.update({
  id: '/api/shipbubble/ping',
  path: '/api/shipbubble/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsUploadImageRoute = ApiProductsUploadImageRouteImport.update({
  id: '/api/products/upload-image',
  path: '/api/products/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramConnectRoute = ApiInstagramConnectRouteImport.update({
  id: '/api/instagram/connect',
  path: '/api/instagram/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramCallbackRoute = ApiInstagramCallbackRouteImport.update({
  id: '/api/instagram/callback',
  path: '/api/instagram/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportStatusRoute = ApiImportStatusRouteImport.update({
  id: '/api/import/status',
  path: '/api/import/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportStartRoute = ApiImportStartRouteImport.update({
  id: '/api/import/start',
  path: '/api/import/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportCsvRoute = ApiImportCsvRouteImport.update({
  id: '/api/import/csv',
  path: '/api/import/csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBumpaConnectRoute = ApiBumpaConnectRouteImport.update({
  id: '/api/bumpa/connect',
  path: '/api/bumpa/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/become-a-creator': typeof BecomeACreatorRoute
  '/become-a-curator': typeof BecomeACuratorRoute
  '/choose-username': typeof ChooseUsernameRoute
  '/create': typeof CreateRouteWithChildren
  '/create-password': typeof CreatePasswordRoute
  '/edit-profile': typeof EditProfileRoute
  '/find-your-fit': typeof FindYourFitRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/name-your-store': typeof NameYourStoreRoute
  '/no-account': typeof NoAccountRoute
  '/offline-videos': typeof OfflineVideosRoute
  '/passkey': typeof PasskeyRoute
  '/previous-index': typeof PreviousIndexRoute
  '/privacy': typeof PrivacyRoute
  '/seller-type': typeof SellerTypeRoute
  '/set-up-store': typeof SetUpStoreRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/store': typeof StoreRouteWithChildren
  '/studio': typeof StudioRoute
  '/switching-roles': typeof SwitchingRolesRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/whats-your-style': typeof WhatsYourStyleRoute
  '/where-did-you-hear-about-us': typeof WhereDidYouHearAboutUsRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/sound-file': typeof ApiSoundFileRoute
  '/api/sounds': typeof ApiSoundsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/create/after-shot': typeof CreateAfterShotRouteWithChildren
  '/create/drafts': typeof CreateDraftsRoute
  '/create/photo-editor': typeof CreatePhotoEditorRoute
  '/create/video-editor': typeof CreateVideoEditorRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/store-profile/$storeUsername': typeof StoreProfileStoreUsernameRoute
  '/store/collections': typeof StoreCollectionsRoute
  '/store/content': typeof StoreContentRoute
  '/store/customers': typeof StoreCustomersRoute
  '/store/discounts': typeof StoreDiscountsRoute
  '/store/finance': typeof StoreFinanceRoute
  '/store/get-the-webapp': typeof StoreGetTheWebappRoute
  '/store/growth': typeof StoreGrowthRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/products': typeof StoreProductsRoute
  '/store/theme': typeof StoreThemeRoute
  '/create/': typeof CreateIndexRoute
  '/store/': typeof StoreIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/bumpa/connect': typeof ApiBumpaConnectRoute
  '/api/import/csv': typeof ApiImportCsvRoute
  '/api/import/start': typeof ApiImportStartRoute
  '/api/import/status': typeof ApiImportStatusRoute
  '/api/instagram/callback': typeof ApiInstagramCallbackRoute
  '/api/instagram/connect': typeof ApiInstagramConnectRoute
  '/api/products/upload-image': typeof ApiProductsUploadImageRoute
  '/api/shipbubble/ping': typeof ApiShipbubblePingRoute
  '/api/shopify/callback': typeof ApiShopifyCallbackRoute
  '/api/shopify/install': typeof ApiShopifyInstallRoute
  '/api/store-theme/upload-image': typeof ApiStoreThemeUploadImageRoute
  '/api/store/payout': typeof ApiStorePayoutRoute
  '/api/support-messages/reply': typeof ApiSupportMessagesReplyRoute
  '/create/after-shot/publish': typeof CreateAfterShotPublishRoute
  '/create/after-shot/studio': typeof CreateAfterShotStudioRoute
  '/store/collections/$id': typeof StoreCollectionsIdRoute
  '/store/collections/new': typeof StoreCollectionsNewRoute
  '/store/locations/new': typeof StoreLocationsNewRoute
  '/store/products/$id': typeof StoreProductsIdRoute
  '/store/products/new': typeof StoreProductsNewRoute
  '/store/products/newcomer': typeof StoreProductsNewcomerRoute
  '/store/products/upload': typeof StoreProductsUploadRoute
  '/create/after-shot/': typeof CreateAfterShotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/become-a-creator': typeof BecomeACreatorRoute
  '/become-a-curator': typeof BecomeACuratorRoute
  '/choose-username': typeof ChooseUsernameRoute
  '/create-password': typeof CreatePasswordRoute
  '/edit-profile': typeof EditProfileRoute
  '/find-your-fit': typeof FindYourFitRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/name-your-store': typeof NameYourStoreRoute
  '/no-account': typeof NoAccountRoute
  '/offline-videos': typeof OfflineVideosRoute
  '/passkey': typeof PasskeyRoute
  '/previous-index': typeof PreviousIndexRoute
  '/privacy': typeof PrivacyRoute
  '/seller-type': typeof SellerTypeRoute
  '/set-up-store': typeof SetUpStoreRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/studio': typeof StudioRoute
  '/switching-roles': typeof SwitchingRolesRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/whats-your-style': typeof WhatsYourStyleRoute
  '/where-did-you-hear-about-us': typeof WhereDidYouHearAboutUsRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/sound-file': typeof ApiSoundFileRoute
  '/api/sounds': typeof ApiSoundsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/create/drafts': typeof CreateDraftsRoute
  '/create/photo-editor': typeof CreatePhotoEditorRoute
  '/create/video-editor': typeof CreateVideoEditorRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/store-profile/$storeUsername': typeof StoreProfileStoreUsernameRoute
  '/store/collections': typeof StoreCollectionsRoute
  '/store/content': typeof StoreContentRoute
  '/store/customers': typeof StoreCustomersRoute
  '/store/discounts': typeof StoreDiscountsRoute
  '/store/finance': typeof StoreFinanceRoute
  '/store/get-the-webapp': typeof StoreGetTheWebappRoute
  '/store/growth': typeof StoreGrowthRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/products': typeof StoreProductsRoute
  '/store/theme': typeof StoreThemeRoute
  '/create': typeof CreateIndexRoute
  '/store': typeof StoreIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/bumpa/connect': typeof ApiBumpaConnectRoute
  '/api/import/csv': typeof ApiImportCsvRoute
  '/api/import/start': typeof ApiImportStartRoute
  '/api/import/status': typeof ApiImportStatusRoute
  '/api/instagram/callback': typeof ApiInstagramCallbackRoute
  '/api/instagram/connect': typeof ApiInstagramConnectRoute
  '/api/products/upload-image': typeof ApiProductsUploadImageRoute
  '/api/shipbubble/ping': typeof ApiShipbubblePingRoute
  '/api/shopify/callback': typeof ApiShopifyCallbackRoute
  '/api/shopify/install': typeof ApiShopifyInstallRoute
  '/api/store-theme/upload-image': typeof ApiStoreThemeUploadImageRoute
  '/api/store/payout': typeof ApiStorePayoutRoute
  '/api/support-messages/reply': typeof ApiSupportMessagesReplyRoute
  '/create/after-shot/publish': typeof CreateAfterShotPublishRoute
  '/create/after-shot/studio': typeof CreateAfterShotStudioRoute
  '/store/collections/$id': typeof StoreCollectionsIdRoute
  '/store/collections/new': typeof StoreCollectionsNewRoute
  '/store/locations/new': typeof StoreLocationsNewRoute
  '/store/products/$id': typeof StoreProductsIdRoute
  '/store/products/new': typeof StoreProductsNewRoute
  '/store/products/newcomer': typeof StoreProductsNewcomerRoute
  '/store/products/upload': typeof StoreProductsUploadRoute
  '/create/after-shot': typeof CreateAfterShotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/become-a-creator': typeof BecomeACreatorRoute
  '/become-a-curator': typeof BecomeACuratorRoute
  '/choose-username': typeof ChooseUsernameRoute
  '/create': typeof CreateRouteWithChildren
  '/create-password': typeof CreatePasswordRoute
  '/edit-profile': typeof EditProfileRoute
  '/find-your-fit': typeof FindYourFitRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/name-your-store': typeof NameYourStoreRoute
  '/no-account': typeof NoAccountRoute
  '/offline-videos': typeof OfflineVideosRoute
  '/passkey': typeof PasskeyRoute
  '/previous-index': typeof PreviousIndexRoute
  '/privacy': typeof PrivacyRoute
  '/seller-type': typeof SellerTypeRoute
  '/set-up-store': typeof SetUpStoreRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/store': typeof StoreRouteWithChildren
  '/studio': typeof StudioRoute
  '/switching-roles': typeof SwitchingRolesRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/whats-your-style': typeof WhatsYourStyleRoute
  '/where-did-you-hear-about-us': typeof WhereDidYouHearAboutUsRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/sound-file': typeof ApiSoundFileRoute
  '/api/sounds': typeof ApiSoundsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/create/after-shot': typeof CreateAfterShotRouteWithChildren
  '/create/drafts': typeof CreateDraftsRoute
  '/create/photo-editor': typeof CreatePhotoEditorRoute
  '/create/video-editor': typeof CreateVideoEditorRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/store-profile/$storeUsername': typeof StoreProfileStoreUsernameRoute
  '/store/collections': typeof StoreCollectionsRoute
  '/store/content': typeof StoreContentRoute
  '/store/customers': typeof StoreCustomersRoute
  '/store/discounts': typeof StoreDiscountsRoute
  '/store/finance': typeof StoreFinanceRoute
  '/store/get-the-webapp': typeof StoreGetTheWebappRoute
  '/store/growth': typeof StoreGrowthRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/products': typeof StoreProductsRoute
  '/store/theme': typeof StoreThemeRoute
  '/create/': typeof CreateIndexRoute
  '/store/': typeof StoreIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/bumpa/connect': typeof ApiBumpaConnectRoute
  '/api/import/csv': typeof ApiImportCsvRoute
  '/api/import/start': typeof ApiImportStartRoute
  '/api/import/status': typeof ApiImportStatusRoute
  '/api/instagram/callback': typeof ApiInstagramCallbackRoute
  '/api/instagram/connect': typeof ApiInstagramConnectRoute
  '/api/products/upload-image': typeof ApiProductsUploadImageRoute
  '/api/shipbubble/ping': typeof ApiShipbubblePingRoute
  '/api/shopify/callback': typeof ApiShopifyCallbackRoute
  '/api/shopify/install': typeof ApiShopifyInstallRoute
  '/api/store-theme/upload-image': typeof ApiStoreThemeUploadImageRoute
  '/api/store/payout': typeof ApiStorePayoutRoute
  '/api/support-messages/reply': typeof ApiSupportMessagesReplyRoute
  '/create/after-shot/publish': typeof CreateAfterShotPublishRoute
  '/create/after-shot/studio': typeof CreateAfterShotStudioRoute
  '/store/collections_/$id': typeof StoreCollectionsIdRoute
  '/store/collections_/new': typeof StoreCollectionsNewRoute
  '/store/locations_/new': typeof StoreLocationsNewRoute
  '/store/products_/$id': typeof StoreProductsIdRoute
  '/store/products_/new': typeof StoreProductsNewRoute
  '/store/products_/newcomer': typeof StoreProductsNewcomerRoute
  '/store/products_/upload': typeof StoreProductsUploadRoute
  '/create/after-shot/': typeof CreateAfterShotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/become-a-creator'
    | '/become-a-curator'
    | '/choose-username'
    | '/create'
    | '/create-password'
    | '/edit-profile'
    | '/find-your-fit'
    | '/home'
    | '/messages'
    | '/name-your-store'
    | '/no-account'
    | '/offline-videos'
    | '/passkey'
    | '/previous-index'
    | '/privacy'
    | '/seller-type'
    | '/set-up-store'
    | '/settings'
    | '/sign-in'
    | '/store'
    | '/studio'
    | '/switching-roles'
    | '/terms'
    | '/welcome'
    | '/whats-your-style'
    | '/where-did-you-hear-about-us'
    | '/api/posts'
    | '/api/sound-file'
    | '/api/sounds'
    | '/auth/callback'
    | '/create/after-shot'
    | '/create/drafts'
    | '/create/photo-editor'
    | '/create/video-editor'
    | '/profile/$username'
    | '/store-profile/$storeUsername'
    | '/store/collections'
    | '/store/content'
    | '/store/customers'
    | '/store/discounts'
    | '/store/finance'
    | '/store/get-the-webapp'
    | '/store/growth'
    | '/store/orders'
    | '/store/products'
    | '/store/theme'
    | '/create/'
    | '/store/'
    | '/api/account/delete'
    | '/api/bumpa/connect'
    | '/api/import/csv'
    | '/api/import/start'
    | '/api/import/status'
    | '/api/instagram/callback'
    | '/api/instagram/connect'
    | '/api/products/upload-image'
    | '/api/shipbubble/ping'
    | '/api/shopify/callback'
    | '/api/shopify/install'
    | '/api/store-theme/upload-image'
    | '/api/store/payout'
    | '/api/support-messages/reply'
    | '/create/after-shot/publish'
    | '/create/after-shot/studio'
    | '/store/collections/$id'
    | '/store/collections/new'
    | '/store/locations/new'
    | '/store/products/$id'
    | '/store/products/new'
    | '/store/products/newcomer'
    | '/store/products/upload'
    | '/create/after-shot/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/become-a-creator'
    | '/become-a-curator'
    | '/choose-username'
    | '/create-password'
    | '/edit-profile'
    | '/find-your-fit'
    | '/home'
    | '/messages'
    | '/name-your-store'
    | '/no-account'
    | '/offline-videos'
    | '/passkey'
    | '/previous-index'
    | '/privacy'
    | '/seller-type'
    | '/set-up-store'
    | '/settings'
    | '/sign-in'
    | '/studio'
    | '/switching-roles'
    | '/terms'
    | '/welcome'
    | '/whats-your-style'
    | '/where-did-you-hear-about-us'
    | '/api/posts'
    | '/api/sound-file'
    | '/api/sounds'
    | '/auth/callback'
    | '/create/drafts'
    | '/create/photo-editor'
    | '/create/video-editor'
    | '/profile/$username'
    | '/store-profile/$storeUsername'
    | '/store/collections'
    | '/store/content'
    | '/store/customers'
    | '/store/discounts'
    | '/store/finance'
    | '/store/get-the-webapp'
    | '/store/growth'
    | '/store/orders'
    | '/store/products'
    | '/store/theme'
    | '/create'
    | '/store'
    | '/api/account/delete'
    | '/api/bumpa/connect'
    | '/api/import/csv'
    | '/api/import/start'
    | '/api/import/status'
    | '/api/instagram/callback'
    | '/api/instagram/connect'
    | '/api/products/upload-image'
    | '/api/shipbubble/ping'
    | '/api/shopify/callback'
    | '/api/shopify/install'
    | '/api/store-theme/upload-image'
    | '/api/store/payout'
    | '/api/support-messages/reply'
    | '/create/after-shot/publish'
    | '/create/after-shot/studio'
    | '/store/collections/$id'
    | '/store/collections/new'
    | '/store/locations/new'
    | '/store/products/$id'
    | '/store/products/new'
    | '/store/products/newcomer'
    | '/store/products/upload'
    | '/create/after-shot'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/become-a-creator'
    | '/become-a-curator'
    | '/choose-username'
    | '/create'
    | '/create-password'
    | '/edit-profile'
    | '/find-your-fit'
    | '/home'
    | '/messages'
    | '/name-your-store'
    | '/no-account'
    | '/offline-videos'
    | '/passkey'
    | '/previous-index'
    | '/privacy'
    | '/seller-type'
    | '/set-up-store'
    | '/settings'
    | '/sign-in'
    | '/store'
    | '/studio'
    | '/switching-roles'
    | '/terms'
    | '/welcome'
    | '/whats-your-style'
    | '/where-did-you-hear-about-us'
    | '/api/posts'
    | '/api/sound-file'
    | '/api/sounds'
    | '/auth/callback'
    | '/create/after-shot'
    | '/create/drafts'
    | '/create/photo-editor'
    | '/create/video-editor'
    | '/profile/$username'
    | '/store-profile/$storeUsername'
    | '/store/collections'
    | '/store/content'
    | '/store/customers'
    | '/store/discounts'
    | '/store/finance'
    | '/store/get-the-webapp'
    | '/store/growth'
    | '/store/orders'
    | '/store/products'
    | '/store/theme'
    | '/create/'
    | '/store/'
    | '/api/account/delete'
    | '/api/bumpa/connect'
    | '/api/import/csv'
    | '/api/import/start'
    | '/api/import/status'
    | '/api/instagram/callback'
    | '/api/instagram/connect'
    | '/api/products/upload-image'
    | '/api/shipbubble/ping'
    | '/api/shopify/callback'
    | '/api/shopify/install'
    | '/api/store-theme/upload-image'
    | '/api/store/payout'
    | '/api/support-messages/reply'
    | '/create/after-shot/publish'
    | '/create/after-shot/studio'
    | '/store/collections_/$id'
    | '/store/collections_/new'
    | '/store/locations_/new'
    | '/store/products_/$id'
    | '/store/products_/new'
    | '/store/products_/newcomer'
    | '/store/products_/upload'
    | '/create/after-shot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BecomeACreatorRoute: typeof BecomeACreatorRoute
  BecomeACuratorRoute: typeof BecomeACuratorRoute
  ChooseUsernameRoute: typeof ChooseUsernameRoute
  CreateRoute: typeof CreateRouteWithChildren
  CreatePasswordRoute: typeof CreatePasswordRoute
  EditProfileRoute: typeof EditProfileRoute
  FindYourFitRoute: typeof FindYourFitRoute
  HomeRoute: typeof HomeRoute
  MessagesRoute: typeof MessagesRoute
  NameYourStoreRoute: typeof NameYourStoreRoute
  NoAccountRoute: typeof NoAccountRoute
  OfflineVideosRoute: typeof OfflineVideosRoute
  PasskeyRoute: typeof PasskeyRoute
  PreviousIndexRoute: typeof PreviousIndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SellerTypeRoute: typeof SellerTypeRoute
  SetUpStoreRoute: typeof SetUpStoreRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  StoreRoute: typeof StoreRouteWithChildren
  StudioRoute: typeof StudioRoute
  SwitchingRolesRoute: typeof SwitchingRolesRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  WhatsYourStyleRoute: typeof WhatsYourStyleRoute
  WhereDidYouHearAboutUsRoute: typeof WhereDidYouHearAboutUsRoute
  ApiPostsRoute: typeof ApiPostsRoute
  ApiSoundFileRoute: typeof ApiSoundFileRoute
  ApiSoundsRoute: typeof ApiSoundsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  StoreProfileStoreUsernameRoute: typeof StoreProfileStoreUsernameRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiBumpaConnectRoute: typeof ApiBumpaConnectRoute
  ApiImportCsvRoute: typeof ApiImportCsvRoute
  ApiImportStartRoute: typeof ApiImportStartRoute
  ApiImportStatusRoute: typeof ApiImportStatusRoute
  ApiInstagramCallbackRoute: typeof ApiInstagramCallbackRoute
  ApiInstagramConnectRoute: typeof ApiInstagramConnectRoute
  ApiProductsUploadImageRoute: typeof ApiProductsUploadImageRoute
  ApiShipbubblePingRoute: typeof ApiShipbubblePingRoute
  ApiShopifyCallbackRoute: typeof ApiShopifyCallbackRoute
  ApiShopifyInstallRoute: typeof ApiShopifyInstallRoute
  ApiStoreThemeUploadImageRoute: typeof ApiStoreThemeUploadImageRoute
  ApiStorePayoutRoute: typeof ApiStorePayoutRoute
  ApiSupportMessagesReplyRoute: typeof ApiSupportMessagesReplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/where-did-you-hear-about-us': {
      id: '/where-did-you-hear-about-us'
      path: '/where-did-you-hear-about-us'
      fullPath: '/where-did-you-hear-about-us'
      preLoaderRoute: typeof WhereDidYouHearAboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whats-your-style': {
      id: '/whats-your-style'
      path: '/whats-your-style'
      fullPath: '/whats-your-style'
      preLoaderRoute: typeof WhatsYourStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switching-roles': {
      id: '/switching-roles'
      path: '/switching-roles'
      fullPath: '/switching-roles'
      preLoaderRoute: typeof SwitchingRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-up-store': {
      id: '/set-up-store'
      path: '/set-up-store'
      fullPath: '/set-up-store'
      preLoaderRoute: typeof SetUpStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-type': {
      id: '/seller-type'
      path: '/seller-type'
      fullPath: '/seller-type'
      preLoaderRoute: typeof SellerTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previous-index': {
      id: '/previous-index'
      path: '/previous-index'
      fullPath: '/previous-index'
      preLoaderRoute: typeof PreviousIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passkey': {
      id: '/passkey'
      path: '/passkey'
      fullPath: '/passkey'
      preLoaderRoute: typeof PasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline-videos': {
      id: '/offline-videos'
      path: '/offline-videos'
      fullPath: '/offline-videos'
      preLoaderRoute: typeof OfflineVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-account': {
      id: '/no-account'
      path: '/no-account'
      fullPath: '/no-account'
      preLoaderRoute: typeof NoAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name-your-store': {
      id: '/name-your-store'
      path: '/name-your-store'
      fullPath: '/name-your-store'
      preLoaderRoute: typeof NameYourStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-your-fit': {
      id: '/find-your-fit'
      path: '/find-your-fit'
      fullPath: '/find-your-fit'
      preLoaderRoute: typeof FindYourFitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-password': {
      id: '/create-password'
      path: '/create-password'
      fullPath: '/create-password'
      preLoaderRoute: typeof CreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-username': {
      id: '/choose-username'
      path: '/choose-username'
      fullPath: '/choose-username'
      preLoaderRoute: typeof ChooseUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-curator': {
      id: '/become-a-curator'
      path: '/become-a-curator'
      fullPath: '/become-a-curator'
      preLoaderRoute: typeof BecomeACuratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-creator': {
      id: '/become-a-creator'
      path: '/become-a-creator'
      fullPath: '/become-a-creator'
      preLoaderRoute: typeof BecomeACreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/store/theme': {
      id: '/store/theme'
      path: '/theme'
      fullPath: '/store/theme'
      preLoaderRoute: typeof StoreThemeRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/products': {
      id: '/store/products'
      path: '/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof StoreProductsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/orders': {
      id: '/store/orders'
      path: '/orders'
      fullPath: '/store/orders'
      preLoaderRoute: typeof StoreOrdersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/growth': {
      id: '/store/growth'
      path: '/growth'
      fullPath: '/store/growth'
      preLoaderRoute: typeof StoreGrowthRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/get-the-webapp': {
      id: '/store/get-the-webapp'
      path: '/get-the-webapp'
      fullPath: '/store/get-the-webapp'
      preLoaderRoute: typeof StoreGetTheWebappRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/finance': {
      id: '/store/finance'
      path: '/finance'
      fullPath: '/store/finance'
      preLoaderRoute: typeof StoreFinanceRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/discounts': {
      id: '/store/discounts'
      path: '/discounts'
      fullPath: '/store/discounts'
      preLoaderRoute: typeof StoreDiscountsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/customers': {
      id: '/store/customers'
      path: '/customers'
      fullPath: '/store/customers'
      preLoaderRoute: typeof StoreCustomersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/content': {
      id: '/store/content'
      path: '/content'
      fullPath: '/store/content'
      preLoaderRoute: typeof StoreContentRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/collections': {
      id: '/store/collections'
      path: '/collections'
      fullPath: '/store/collections'
      preLoaderRoute: typeof StoreCollectionsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store-profile/$storeUsername': {
      id: '/store-profile/$storeUsername'
      path: '/store-profile/$storeUsername'
      fullPath: '/store-profile/$storeUsername'
      preLoaderRoute: typeof StoreProfileStoreUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/video-editor': {
      id: '/create/video-editor'
      path: '/video-editor'
      fullPath: '/create/video-editor'
      preLoaderRoute: typeof CreateVideoEditorRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/photo-editor': {
      id: '/create/photo-editor'
      path: '/photo-editor'
      fullPath: '/create/photo-editor'
      preLoaderRoute: typeof CreatePhotoEditorRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/drafts': {
      id: '/create/drafts'
      path: '/drafts'
      fullPath: '/create/drafts'
      preLoaderRoute: typeof CreateDraftsRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/after-shot': {
      id: '/create/after-shot'
      path: '/after-shot'
      fullPath: '/create/after-shot'
      preLoaderRoute: typeof CreateAfterShotRouteImport
      parentRoute: typeof CreateRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sounds': {
      id: '/api/sounds'
      path: '/api/sounds'
      fullPath: '/api/sounds'
      preLoaderRoute: typeof ApiSoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sound-file': {
      id: '/api/sound-file'
      path: '/api/sound-file'
      fullPath: '/api/sound-file'
      preLoaderRoute: typeof ApiSoundFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/after-shot/': {
      id: '/create/after-shot/'
      path: '/'
      fullPath: '/create/after-shot/'
      preLoaderRoute: typeof CreateAfterShotIndexRouteImport
      parentRoute: typeof CreateAfterShotRoute
    }
    '/store/products_/upload': {
      id: '/store/products_/upload'
      path: '/products/upload'
      fullPath: '/store/products/upload'
      preLoaderRoute: typeof StoreProductsUploadRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/products_/newcomer': {
      id: '/store/products_/newcomer'
      path: '/products/newcomer'
      fullPath: '/store/products/newcomer'
      preLoaderRoute: typeof StoreProductsNewcomerRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/products_/new': {
      id: '/store/products_/new'
      path: '/products/new'
      fullPath: '/store/products/new'
      preLoaderRoute: typeof StoreProductsNewRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/products_/$id': {
      id: '/store/products_/$id'
      path: '/products/$id'
      fullPath: '/store/products/$id'
      preLoaderRoute: typeof StoreProductsIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/locations_/new': {
      id: '/store/locations_/new'
      path: '/locations/new'
      fullPath: '/store/locations/new'
      preLoaderRoute: typeof StoreLocationsNewRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/collections_/new': {
      id: '/store/collections_/new'
      path: '/collections/new'
      fullPath: '/store/collections/new'
      preLoaderRoute: typeof StoreCollectionsNewRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/collections_/$id': {
      id: '/store/collections_/$id'
      path: '/collections/$id'
      fullPath: '/store/collections/$id'
      preLoaderRoute: typeof StoreCollectionsIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/create/after-shot/studio': {
      id: '/create/after-shot/studio'
      path: '/studio'
      fullPath: '/create/after-shot/studio'
      preLoaderRoute: typeof CreateAfterShotStudioRouteImport
      parentRoute: typeof CreateAfterShotRoute
    }
    '/create/after-shot/publish': {
      id: '/create/after-shot/publish'
      path: '/publish'
      fullPath: '/create/after-shot/publish'
      preLoaderRoute: typeof CreateAfterShotPublishRouteImport
      parentRoute: typeof CreateAfterShotRoute
    }
    '/api/support-messages/reply': {
      id: '/api/support-messages/reply'
      path: '/api/support-messages/reply'
      fullPath: '/api/support-messages/reply'
      preLoaderRoute: typeof ApiSupportMessagesReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/payout': {
      id: '/api/store/payout'
      path: '/api/store/payout'
      fullPath: '/api/store/payout'
      preLoaderRoute: typeof ApiStorePayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store-theme/upload-image': {
      id: '/api/store-theme/upload-image'
      path: '/api/store-theme/upload-image'
      fullPath: '/api/store-theme/upload-image'
      preLoaderRoute: typeof ApiStoreThemeUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/install': {
      id: '/api/shopify/install'
      path: '/api/shopify/install'
      fullPath: '/api/shopify/install'
      preLoaderRoute: typeof ApiShopifyInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/callback': {
      id: '/api/shopify/callback'
      path: '/api/shopify/callback'
      fullPath: '/api/shopify/callback'
      preLoaderRoute: typeof ApiShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipbubble/ping': {
      id: '/api/shipbubble/ping'
      path: '/api/shipbubble/ping'
      fullPath: '/api/shipbubble/ping'
      preLoaderRoute: typeof ApiShipbubblePingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/upload-image': {
      id: '/api/products/upload-image'
      path: '/api/products/upload-image'
      fullPath: '/api/products/upload-image'
      preLoaderRoute: typeof ApiProductsUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram/connect': {
      id: '/api/instagram/connect'
      path: '/api/instagram/connect'
      fullPath: '/api/instagram/connect'
      preLoaderRoute: typeof ApiInstagramConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram/callback': {
      id: '/api/instagram/callback'
      path: '/api/instagram/callback'
      fullPath: '/api/instagram/callback'
      preLoaderRoute: typeof ApiInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/status': {
      id: '/api/import/status'
      path: '/api/import/status'
      fullPath: '/api/import/status'
      preLoaderRoute: typeof ApiImportStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/start': {
      id: '/api/import/start'
      path: '/api/import/start'
      fullPath: '/api/import/start'
      preLoaderRoute: typeof ApiImportStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/csv': {
      id: '/api/import/csv'
      path: '/api/import/csv'
      fullPath: '/api/import/csv'
      preLoaderRoute: typeof ApiImportCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bumpa/connect': {
      id: '/api/bumpa/connect'
      path: '/api/bumpa/connect'
      fullPath: '/api/bumpa/connect'
      preLoaderRoute: typeof ApiBumpaConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CreateAfterShotRouteChildren {
  CreateAfterShotPublishRoute: typeof CreateAfterShotPublishRoute
  CreateAfterShotStudioRoute: typeof CreateAfterShotStudioRoute
  CreateAfterShotIndexRoute: typeof CreateAfterShotIndexRoute
}

const CreateAfterShotRouteChildren: CreateAfterShotRouteChildren = {
  CreateAfterShotPublishRoute: CreateAfterShotPublishRoute,
  CreateAfterShotStudioRoute: CreateAfterShotStudioRoute,
  CreateAfterShotIndexRoute: CreateAfterShotIndexRoute,
}

const CreateAfterShotRouteWithChildren = CreateAfterShotRoute._addFileChildren(
  CreateAfterShotRouteChildren,
)

interface CreateRouteChildren {
  CreateAfterShotRoute: typeof CreateAfterShotRouteWithChildren
  CreateDraftsRoute: typeof CreateDraftsRoute
  CreatePhotoEditorRoute: typeof CreatePhotoEditorRoute
  CreateVideoEditorRoute: typeof CreateVideoEditorRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateAfterShotRoute: CreateAfterShotRouteWithChildren,
  CreateDraftsRoute: CreateDraftsRoute,
  CreatePhotoEditorRoute: CreatePhotoEditorRoute,
  CreateVideoEditorRoute: CreateVideoEditorRoute,
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

interface StoreRouteChildren {
  StoreCollectionsRoute: typeof StoreCollectionsRoute
  StoreContentRoute: typeof StoreContentRoute
  StoreCustomersRoute: typeof StoreCustomersRoute
  StoreDiscountsRoute: typeof StoreDiscountsRoute
  StoreFinanceRoute: typeof StoreFinanceRoute
  StoreGetTheWebappRoute: typeof StoreGetTheWebappRoute
  StoreGrowthRoute: typeof StoreGrowthRoute
  StoreOrdersRoute: typeof StoreOrdersRoute
  StoreProductsRoute: typeof StoreProductsRoute
  StoreThemeRoute: typeof StoreThemeRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreCollectionsIdRoute: typeof StoreCollectionsIdRoute
  StoreCollectionsNewRoute: typeof StoreCollectionsNewRoute
  StoreLocationsNewRoute: typeof StoreLocationsNewRoute
  StoreProductsIdRoute: typeof StoreProductsIdRoute
  StoreProductsNewRoute: typeof StoreProductsNewRoute
  StoreProductsNewcomerRoute: typeof StoreProductsNewcomerRoute
  StoreProductsUploadRoute: typeof StoreProductsUploadRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreCollectionsRoute: StoreCollectionsRoute,
  StoreContentRoute: StoreContentRoute,
  StoreCustomersRoute: StoreCustomersRoute,
  StoreDiscountsRoute: StoreDiscountsRoute,
  StoreFinanceRoute: StoreFinanceRoute,
  StoreGetTheWebappRoute: StoreGetTheWebappRoute,
  StoreGrowthRoute: StoreGrowthRoute,
  StoreOrdersRoute: StoreOrdersRoute,
  StoreProductsRoute: StoreProductsRoute,
  StoreThemeRoute: StoreThemeRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreCollectionsIdRoute: StoreCollectionsIdRoute,
  StoreCollectionsNewRoute: StoreCollectionsNewRoute,
  StoreLocationsNewRoute: StoreLocationsNewRoute,
  StoreProductsIdRoute: StoreProductsIdRoute,
  StoreProductsNewRoute: StoreProductsNewRoute,
  StoreProductsNewcomerRoute: StoreProductsNewcomerRoute,
  StoreProductsUploadRoute: StoreProductsUploadRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BecomeACreatorRoute: BecomeACreatorRoute,
  BecomeACuratorRoute: BecomeACuratorRoute,
  ChooseUsernameRoute: ChooseUsernameRoute,
  CreateRoute: CreateRouteWithChildren,
  CreatePasswordRoute: CreatePasswordRoute,
  EditProfileRoute: EditProfileRoute,
  FindYourFitRoute: FindYourFitRoute,
  HomeRoute: HomeRoute,
  MessagesRoute: MessagesRoute,
  NameYourStoreRoute: NameYourStoreRoute,
  NoAccountRoute: NoAccountRoute,
  OfflineVideosRoute: OfflineVideosRoute,
  PasskeyRoute: PasskeyRoute,
  PreviousIndexRoute: PreviousIndexRoute,
  PrivacyRoute: PrivacyRoute,
  SellerTypeRoute: SellerTypeRoute,
  SetUpStoreRoute: SetUpStoreRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  StoreRoute: StoreRouteWithChildren,
  StudioRoute: StudioRoute,
  SwitchingRolesRoute: SwitchingRolesRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  WhatsYourStyleRoute: WhatsYourStyleRoute,
  WhereDidYouHearAboutUsRoute: WhereDidYouHearAboutUsRoute,
  ApiPostsRoute: ApiPostsRoute,
  ApiSoundFileRoute: ApiSoundFileRoute,
  ApiSoundsRoute: ApiSoundsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  StoreProfileStoreUsernameRoute: StoreProfileStoreUsernameRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiBumpaConnectRoute: ApiBumpaConnectRoute,
  ApiImportCsvRoute: ApiImportCsvRoute,
  ApiImportStartRoute: ApiImportStartRoute,
  ApiImportStatusRoute: ApiImportStatusRoute,
  ApiInstagramCallbackRoute: ApiInstagramCallbackRoute,
  ApiInstagramConnectRoute: ApiInstagramConnectRoute,
  ApiProductsUploadImageRoute: ApiProductsUploadImageRoute,
  ApiShipbubblePingRoute: ApiShipbubblePingRoute,
  ApiShopifyCallbackRoute: ApiShopifyCallbackRoute,
  ApiShopifyInstallRoute: ApiShopifyInstallRoute,
  ApiStoreThemeUploadImageRoute: ApiStoreThemeUploadImageRoute,
  ApiStorePayoutRoute: ApiStorePayoutRoute,
  ApiSupportMessagesReplyRoute: ApiSupportMessagesReplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
