/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BecomeACreatorRouteImport } from './routes/become-a-creator'
import { Route as BecomeACuratorRouteImport } from './routes/become-a-curator'
import { Route as ChooseUsernameRouteImport } from './routes/choose-username'
import { Route as NameYourStoreRouteImport } from './routes/name-your-store'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SetUpStoreRouteImport } from './routes/set-up-store'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeACreatorRoute = BecomeACreatorRouteImport.update({
  id: '/become-a-creator',
  path: '/become-a-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeACuratorRoute = BecomeACuratorRouteImport.update({
  id: '/become-a-curator',
  path: '/become-a-curator',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseUsernameRoute = ChooseUsernameRouteImport.update({
  id: '/choose-username',
  path: '/choose-username',
  getParentRoute: () => rootRouteImport,
} as any)
const NameYourStoreRoute = NameYourStoreRouteImport.update({
  id: '/name-your-store',
  path: '/name-your-store',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SetUpStoreRoute = SetUpStoreRouteImport.update({
  id: '/set-up-store',
  path: '/set-up-store',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-a-creator': typeof BecomeACreatorRoute
  '/become-a-curator': typeof BecomeACuratorRoute
  '/choose-username': typeof ChooseUsernameRoute
  '/name-your-store': typeof NameYourStoreRoute
  '/privacy': typeof PrivacyRoute
  '/set-up-store': typeof SetUpStoreRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-a-creator': typeof BecomeACreatorRoute
  '/become-a-curator': typeof BecomeACuratorRoute
  '/choose-username': typeof ChooseUsernameRoute
  '/name-your-store': typeof NameYourStoreRoute
  '/privacy': typeof PrivacyRoute
  '/set-up-store': typeof SetUpStoreRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-a-creator': typeof BecomeACreatorRoute
  '/become-a-curator': typeof BecomeACuratorRoute
  '/choose-username': typeof ChooseUsernameRoute
  '/name-your-store': typeof NameYourStoreRoute
  '/privacy': typeof PrivacyRoute
  '/set-up-store': typeof SetUpStoreRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-a-creator'
    | '/become-a-curator'
    | '/choose-username'
    | '/name-your-store'
    | '/privacy'
    | '/set-up-store'
    | '/terms'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-a-creator'
    | '/become-a-curator'
    | '/choose-username'
    | '/name-your-store'
    | '/privacy'
    | '/set-up-store'
    | '/terms'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/become-a-creator'
    | '/become-a-curator'
    | '/choose-username'
    | '/name-your-store'
    | '/privacy'
    | '/set-up-store'
    | '/terms'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeACreatorRoute: typeof BecomeACreatorRoute
  BecomeACuratorRoute: typeof BecomeACuratorRoute
  ChooseUsernameRoute: typeof ChooseUsernameRoute
  NameYourStoreRoute: typeof NameYourStoreRoute
  PrivacyRoute: typeof PrivacyRoute
  SetUpStoreRoute: typeof SetUpStoreRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-creator': {
      id: '/become-a-creator'
      path: '/become-a-creator'
      fullPath: '/become-a-creator'
      preLoaderRoute: typeof BecomeACreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-curator': {
      id: '/become-a-curator'
      path: '/become-a-curator'
      fullPath: '/become-a-curator'
      preLoaderRoute: typeof BecomeACuratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-username': {
      id: '/choose-username'
      path: '/choose-username'
      fullPath: '/choose-username'
      preLoaderRoute: typeof ChooseUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name-your-store': {
      id: '/name-your-store'
      path: '/name-your-store'
      fullPath: '/name-your-store'
      preLoaderRoute: typeof NameYourStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-up-store': {
      id: '/set-up-store'
      path: '/set-up-store'
      fullPath: '/set-up-store'
      preLoaderRoute: typeof SetUpStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeACreatorRoute: BecomeACreatorRoute,
  BecomeACuratorRoute: BecomeACuratorRoute,
  ChooseUsernameRoute: ChooseUsernameRoute,
  NameYourStoreRoute: NameYourStoreRoute,
  PrivacyRoute: PrivacyRoute,
  SetUpStoreRoute: SetUpStoreRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
